// Code generated by ent, DO NOT EDIT.

package dontstarvemod

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dontstarvemod type in the database.
	Label = "dont_starve_mod"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldWorkshopID holds the string denoting the workshop_id field in the database.
	FieldWorkshopID = "workshop_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTimeCreated holds the string denoting the time_created field in the database.
	FieldTimeCreated = "time_created"
	// FieldTimeUpdated holds the string denoting the time_updated field in the database.
	FieldTimeUpdated = "time_updated"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldDownloaded holds the string denoting the downloaded field in the database.
	FieldDownloaded = "downloaded"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldRawConfig holds the string denoting the raw_config field in the database.
	FieldRawConfig = "raw_config"
	// EdgeArchives holds the string denoting the archives edge name in mutations.
	EdgeArchives = "archives"
	// Table holds the table name of the dontstarvemod in the database.
	Table = "dont_starve_mods"
	// ArchivesTable is the table that holds the archives relation/edge. The primary key declared below.
	ArchivesTable = "dont_starve_archive_mods"
	// ArchivesInverseTable is the table name for the DontStarveArchive entity.
	// It exists in this package in order to avoid circular dependency with the "dontstarvearchive" package.
	ArchivesInverseTable = "dont_starve_archives"
)

// Columns holds all SQL columns for dontstarvemod fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldWorkshopID,
	FieldName,
	FieldTimeCreated,
	FieldTimeUpdated,
	FieldImage,
	FieldDescription,
	FieldAuthor,
	FieldVersion,
	FieldDownloaded,
	FieldConfig,
	FieldRawConfig,
}

var (
	// ArchivesPrimaryKey and ArchivesColumn2 are the table columns denoting the
	// primary key for the archives relation (M2M).
	ArchivesPrimaryKey = []string{"dont_starve_archive_id", "dont_starve_mod_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the DontStarveMod queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWorkshopID orders the results by the workshop_id field.
func ByWorkshopID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkshopID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTimeCreated orders the results by the time_created field.
func ByTimeCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeCreated, opts...).ToFunc()
}

// ByTimeUpdated orders the results by the time_updated field.
func ByTimeUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeUpdated, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByDownloaded orders the results by the downloaded field.
func ByDownloaded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloaded, opts...).ToFunc()
}

// ByRawConfig orders the results by the raw_config field.
func ByRawConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawConfig, opts...).ToFunc()
}

// ByArchivesCount orders the results by archives count.
func ByArchivesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArchivesStep(), opts...)
	}
}

// ByArchives orders the results by archives terms.
func ByArchives(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArchivesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newArchivesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArchivesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ArchivesTable, ArchivesPrimaryKey...),
	)
}
