// Code generated by ent, DO NOT EDIT.

package dontstarvemod

import (
	"aurora-admin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkshopID applies equality check predicate on the "workshop_id" field. It's identical to WorkshopIDEQ.
func WorkshopID(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldWorkshopID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldName, v))
}

// TimeCreated applies equality check predicate on the "time_created" field. It's identical to TimeCreatedEQ.
func TimeCreated(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldTimeCreated, v))
}

// TimeUpdated applies equality check predicate on the "time_updated" field. It's identical to TimeUpdatedEQ.
func TimeUpdated(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldTimeUpdated, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldImage, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldDescription, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldAuthor, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldVersion, v))
}

// Downloaded applies equality check predicate on the "downloaded" field. It's identical to DownloadedEQ.
func Downloaded(v bool) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldDownloaded, v))
}

// RawConfig applies equality check predicate on the "raw_config" field. It's identical to RawConfigEQ.
func RawConfig(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldRawConfig, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkshopIDEQ applies the EQ predicate on the "workshop_id" field.
func WorkshopIDEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldWorkshopID, v))
}

// WorkshopIDNEQ applies the NEQ predicate on the "workshop_id" field.
func WorkshopIDNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldWorkshopID, v))
}

// WorkshopIDIn applies the In predicate on the "workshop_id" field.
func WorkshopIDIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldWorkshopID, vs...))
}

// WorkshopIDNotIn applies the NotIn predicate on the "workshop_id" field.
func WorkshopIDNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldWorkshopID, vs...))
}

// WorkshopIDGT applies the GT predicate on the "workshop_id" field.
func WorkshopIDGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldWorkshopID, v))
}

// WorkshopIDGTE applies the GTE predicate on the "workshop_id" field.
func WorkshopIDGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldWorkshopID, v))
}

// WorkshopIDLT applies the LT predicate on the "workshop_id" field.
func WorkshopIDLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldWorkshopID, v))
}

// WorkshopIDLTE applies the LTE predicate on the "workshop_id" field.
func WorkshopIDLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldWorkshopID, v))
}

// WorkshopIDContains applies the Contains predicate on the "workshop_id" field.
func WorkshopIDContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldWorkshopID, v))
}

// WorkshopIDHasPrefix applies the HasPrefix predicate on the "workshop_id" field.
func WorkshopIDHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldWorkshopID, v))
}

// WorkshopIDHasSuffix applies the HasSuffix predicate on the "workshop_id" field.
func WorkshopIDHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldWorkshopID, v))
}

// WorkshopIDEqualFold applies the EqualFold predicate on the "workshop_id" field.
func WorkshopIDEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldWorkshopID, v))
}

// WorkshopIDContainsFold applies the ContainsFold predicate on the "workshop_id" field.
func WorkshopIDContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldWorkshopID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldName, v))
}

// TimeCreatedEQ applies the EQ predicate on the "time_created" field.
func TimeCreatedEQ(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldTimeCreated, v))
}

// TimeCreatedNEQ applies the NEQ predicate on the "time_created" field.
func TimeCreatedNEQ(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldTimeCreated, v))
}

// TimeCreatedIn applies the In predicate on the "time_created" field.
func TimeCreatedIn(vs ...int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldTimeCreated, vs...))
}

// TimeCreatedNotIn applies the NotIn predicate on the "time_created" field.
func TimeCreatedNotIn(vs ...int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldTimeCreated, vs...))
}

// TimeCreatedGT applies the GT predicate on the "time_created" field.
func TimeCreatedGT(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldTimeCreated, v))
}

// TimeCreatedGTE applies the GTE predicate on the "time_created" field.
func TimeCreatedGTE(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldTimeCreated, v))
}

// TimeCreatedLT applies the LT predicate on the "time_created" field.
func TimeCreatedLT(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldTimeCreated, v))
}

// TimeCreatedLTE applies the LTE predicate on the "time_created" field.
func TimeCreatedLTE(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldTimeCreated, v))
}

// TimeCreatedIsNil applies the IsNil predicate on the "time_created" field.
func TimeCreatedIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldTimeCreated))
}

// TimeCreatedNotNil applies the NotNil predicate on the "time_created" field.
func TimeCreatedNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldTimeCreated))
}

// TimeUpdatedEQ applies the EQ predicate on the "time_updated" field.
func TimeUpdatedEQ(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldTimeUpdated, v))
}

// TimeUpdatedNEQ applies the NEQ predicate on the "time_updated" field.
func TimeUpdatedNEQ(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldTimeUpdated, v))
}

// TimeUpdatedIn applies the In predicate on the "time_updated" field.
func TimeUpdatedIn(vs ...int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldTimeUpdated, vs...))
}

// TimeUpdatedNotIn applies the NotIn predicate on the "time_updated" field.
func TimeUpdatedNotIn(vs ...int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldTimeUpdated, vs...))
}

// TimeUpdatedGT applies the GT predicate on the "time_updated" field.
func TimeUpdatedGT(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldTimeUpdated, v))
}

// TimeUpdatedGTE applies the GTE predicate on the "time_updated" field.
func TimeUpdatedGTE(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldTimeUpdated, v))
}

// TimeUpdatedLT applies the LT predicate on the "time_updated" field.
func TimeUpdatedLT(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldTimeUpdated, v))
}

// TimeUpdatedLTE applies the LTE predicate on the "time_updated" field.
func TimeUpdatedLTE(v int) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldTimeUpdated, v))
}

// TimeUpdatedIsNil applies the IsNil predicate on the "time_updated" field.
func TimeUpdatedIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldTimeUpdated))
}

// TimeUpdatedNotNil applies the NotNil predicate on the "time_updated" field.
func TimeUpdatedNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldTimeUpdated))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldImage, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldDescription, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorIsNil applies the IsNil predicate on the "author" field.
func AuthorIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldAuthor))
}

// AuthorNotNil applies the NotNil predicate on the "author" field.
func AuthorNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldAuthor))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldAuthor, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionIsNil applies the IsNil predicate on the "version" field.
func VersionIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldVersion))
}

// VersionNotNil applies the NotNil predicate on the "version" field.
func VersionNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldVersion))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldVersion, v))
}

// DownloadedEQ applies the EQ predicate on the "downloaded" field.
func DownloadedEQ(v bool) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldDownloaded, v))
}

// DownloadedNEQ applies the NEQ predicate on the "downloaded" field.
func DownloadedNEQ(v bool) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldDownloaded, v))
}

// DownloadedIsNil applies the IsNil predicate on the "downloaded" field.
func DownloadedIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldDownloaded))
}

// DownloadedNotNil applies the NotNil predicate on the "downloaded" field.
func DownloadedNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldDownloaded))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldConfig))
}

// RawConfigEQ applies the EQ predicate on the "raw_config" field.
func RawConfigEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEQ(FieldRawConfig, v))
}

// RawConfigNEQ applies the NEQ predicate on the "raw_config" field.
func RawConfigNEQ(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNEQ(FieldRawConfig, v))
}

// RawConfigIn applies the In predicate on the "raw_config" field.
func RawConfigIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIn(FieldRawConfig, vs...))
}

// RawConfigNotIn applies the NotIn predicate on the "raw_config" field.
func RawConfigNotIn(vs ...string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotIn(FieldRawConfig, vs...))
}

// RawConfigGT applies the GT predicate on the "raw_config" field.
func RawConfigGT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGT(FieldRawConfig, v))
}

// RawConfigGTE applies the GTE predicate on the "raw_config" field.
func RawConfigGTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldGTE(FieldRawConfig, v))
}

// RawConfigLT applies the LT predicate on the "raw_config" field.
func RawConfigLT(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLT(FieldRawConfig, v))
}

// RawConfigLTE applies the LTE predicate on the "raw_config" field.
func RawConfigLTE(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldLTE(FieldRawConfig, v))
}

// RawConfigContains applies the Contains predicate on the "raw_config" field.
func RawConfigContains(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContains(FieldRawConfig, v))
}

// RawConfigHasPrefix applies the HasPrefix predicate on the "raw_config" field.
func RawConfigHasPrefix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasPrefix(FieldRawConfig, v))
}

// RawConfigHasSuffix applies the HasSuffix predicate on the "raw_config" field.
func RawConfigHasSuffix(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldHasSuffix(FieldRawConfig, v))
}

// RawConfigIsNil applies the IsNil predicate on the "raw_config" field.
func RawConfigIsNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldIsNull(FieldRawConfig))
}

// RawConfigNotNil applies the NotNil predicate on the "raw_config" field.
func RawConfigNotNil() predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldNotNull(FieldRawConfig))
}

// RawConfigEqualFold applies the EqualFold predicate on the "raw_config" field.
func RawConfigEqualFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldEqualFold(FieldRawConfig, v))
}

// RawConfigContainsFold applies the ContainsFold predicate on the "raw_config" field.
func RawConfigContainsFold(v string) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.FieldContainsFold(FieldRawConfig, v))
}

// HasArchives applies the HasEdge predicate on the "archives" edge.
func HasArchives() predicate.DontStarveMod {
	return predicate.DontStarveMod(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ArchivesTable, ArchivesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchivesWith applies the HasEdge predicate on the "archives" edge with a given conditions (other predicates).
func HasArchivesWith(preds ...predicate.DontStarveArchive) predicate.DontStarveMod {
	return predicate.DontStarveMod(func(s *sql.Selector) {
		step := newArchivesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DontStarveMod) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DontStarveMod) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DontStarveMod) predicate.DontStarveMod {
	return predicate.DontStarveMod(sql.NotPredicates(p))
}
