// Code generated by ent, DO NOT EDIT.

package dontstarveadmin

import (
	"aurora-admin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldName, v))
}

// KleiID applies equality check predicate on the "klei_id" field. It's identical to KleiIDEQ.
func KleiID(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldKleiID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldContainsFold(FieldName, v))
}

// KleiIDEQ applies the EQ predicate on the "klei_id" field.
func KleiIDEQ(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEQ(FieldKleiID, v))
}

// KleiIDNEQ applies the NEQ predicate on the "klei_id" field.
func KleiIDNEQ(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNEQ(FieldKleiID, v))
}

// KleiIDIn applies the In predicate on the "klei_id" field.
func KleiIDIn(vs ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldIn(FieldKleiID, vs...))
}

// KleiIDNotIn applies the NotIn predicate on the "klei_id" field.
func KleiIDNotIn(vs ...string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldNotIn(FieldKleiID, vs...))
}

// KleiIDGT applies the GT predicate on the "klei_id" field.
func KleiIDGT(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGT(FieldKleiID, v))
}

// KleiIDGTE applies the GTE predicate on the "klei_id" field.
func KleiIDGTE(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldGTE(FieldKleiID, v))
}

// KleiIDLT applies the LT predicate on the "klei_id" field.
func KleiIDLT(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLT(FieldKleiID, v))
}

// KleiIDLTE applies the LTE predicate on the "klei_id" field.
func KleiIDLTE(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldLTE(FieldKleiID, v))
}

// KleiIDContains applies the Contains predicate on the "klei_id" field.
func KleiIDContains(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldContains(FieldKleiID, v))
}

// KleiIDHasPrefix applies the HasPrefix predicate on the "klei_id" field.
func KleiIDHasPrefix(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldHasPrefix(FieldKleiID, v))
}

// KleiIDHasSuffix applies the HasSuffix predicate on the "klei_id" field.
func KleiIDHasSuffix(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldHasSuffix(FieldKleiID, v))
}

// KleiIDEqualFold applies the EqualFold predicate on the "klei_id" field.
func KleiIDEqualFold(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldEqualFold(FieldKleiID, v))
}

// KleiIDContainsFold applies the ContainsFold predicate on the "klei_id" field.
func KleiIDContainsFold(v string) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.FieldContainsFold(FieldKleiID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DontStarveAdmin) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DontStarveAdmin) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DontStarveAdmin) predicate.DontStarveAdmin {
	return predicate.DontStarveAdmin(sql.NotPredicates(p))
}
