// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DontStarveAdminsColumns holds the columns for the "dont_starve_admins" table.
	DontStarveAdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "klei_id", Type: field.TypeString, Unique: true},
	}
	// DontStarveAdminsTable holds the schema information for the "dont_starve_admins" table.
	DontStarveAdminsTable = &schema.Table{
		Name:       "dont_starve_admins",
		Columns:    DontStarveAdminsColumns,
		PrimaryKey: []*schema.Column{DontStarveAdminsColumns[0]},
	}
	// DontStarveArchivesColumns holds the columns for the "dont_starve_archives" table.
	DontStarveArchivesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "cluster_name", Type: field.TypeString, Nullable: true},
		{Name: "cluster_password", Type: field.TypeString, Nullable: true},
		{Name: "cluster_description", Type: field.TypeString, Nullable: true},
		{Name: "max_players", Type: field.TypeInt, Nullable: true},
		{Name: "pvp", Type: field.TypeBool, Nullable: true},
		{Name: "world", Type: field.TypeJSON, Nullable: true},
	}
	// DontStarveArchivesTable holds the schema information for the "dont_starve_archives" table.
	DontStarveArchivesTable = &schema.Table{
		Name:       "dont_starve_archives",
		Columns:    DontStarveArchivesColumns,
		PrimaryKey: []*schema.Column{DontStarveArchivesColumns[0]},
	}
	// DontStarveModsColumns holds the columns for the "dont_starve_mods" table.
	DontStarveModsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "workshop_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "time_created", Type: field.TypeInt, Nullable: true},
		{Name: "time_updated", Type: field.TypeInt, Nullable: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "version", Type: field.TypeString, Nullable: true},
		{Name: "downloaded", Type: field.TypeBool, Nullable: true},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "raw_config", Type: field.TypeString, Nullable: true},
	}
	// DontStarveModsTable holds the schema information for the "dont_starve_mods" table.
	DontStarveModsTable = &schema.Table{
		Name:       "dont_starve_mods",
		Columns:    DontStarveModsColumns,
		PrimaryKey: []*schema.Column{DontStarveModsColumns[0]},
	}
	// DontStarveArchiveModsColumns holds the columns for the "dont_starve_archive_mods" table.
	DontStarveArchiveModsColumns = []*schema.Column{
		{Name: "dont_starve_archive_id", Type: field.TypeString},
		{Name: "dont_starve_mod_id", Type: field.TypeString},
	}
	// DontStarveArchiveModsTable holds the schema information for the "dont_starve_archive_mods" table.
	DontStarveArchiveModsTable = &schema.Table{
		Name:       "dont_starve_archive_mods",
		Columns:    DontStarveArchiveModsColumns,
		PrimaryKey: []*schema.Column{DontStarveArchiveModsColumns[0], DontStarveArchiveModsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dont_starve_archive_mods_dont_starve_archive_id",
				Columns:    []*schema.Column{DontStarveArchiveModsColumns[0]},
				RefColumns: []*schema.Column{DontStarveArchivesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "dont_starve_archive_mods_dont_starve_mod_id",
				Columns:    []*schema.Column{DontStarveArchiveModsColumns[1]},
				RefColumns: []*schema.Column{DontStarveModsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DontStarveAdminsTable,
		DontStarveArchivesTable,
		DontStarveModsTable,
		DontStarveArchiveModsTable,
	}
)

func init() {
	DontStarveArchiveModsTable.ForeignKeys[0].RefTable = DontStarveArchivesTable
	DontStarveArchiveModsTable.ForeignKeys[1].RefTable = DontStarveModsTable
}
