// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"aurora-admin/ent/migrate"

	"aurora-admin/ent/dontstarveadmin"
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DontStarveAdmin is the client for interacting with the DontStarveAdmin builders.
	DontStarveAdmin *DontStarveAdminClient
	// DontStarveArchive is the client for interacting with the DontStarveArchive builders.
	DontStarveArchive *DontStarveArchiveClient
	// DontStarveMod is the client for interacting with the DontStarveMod builders.
	DontStarveMod *DontStarveModClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DontStarveAdmin = NewDontStarveAdminClient(c.config)
	c.DontStarveArchive = NewDontStarveArchiveClient(c.config)
	c.DontStarveMod = NewDontStarveModClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		DontStarveAdmin:   NewDontStarveAdminClient(cfg),
		DontStarveArchive: NewDontStarveArchiveClient(cfg),
		DontStarveMod:     NewDontStarveModClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		DontStarveAdmin:   NewDontStarveAdminClient(cfg),
		DontStarveArchive: NewDontStarveArchiveClient(cfg),
		DontStarveMod:     NewDontStarveModClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DontStarveAdmin.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DontStarveAdmin.Use(hooks...)
	c.DontStarveArchive.Use(hooks...)
	c.DontStarveMod.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DontStarveAdmin.Intercept(interceptors...)
	c.DontStarveArchive.Intercept(interceptors...)
	c.DontStarveMod.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DontStarveAdminMutation:
		return c.DontStarveAdmin.mutate(ctx, m)
	case *DontStarveArchiveMutation:
		return c.DontStarveArchive.mutate(ctx, m)
	case *DontStarveModMutation:
		return c.DontStarveMod.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DontStarveAdminClient is a client for the DontStarveAdmin schema.
type DontStarveAdminClient struct {
	config
}

// NewDontStarveAdminClient returns a client for the DontStarveAdmin from the given config.
func NewDontStarveAdminClient(c config) *DontStarveAdminClient {
	return &DontStarveAdminClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dontstarveadmin.Hooks(f(g(h())))`.
func (c *DontStarveAdminClient) Use(hooks ...Hook) {
	c.hooks.DontStarveAdmin = append(c.hooks.DontStarveAdmin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dontstarveadmin.Intercept(f(g(h())))`.
func (c *DontStarveAdminClient) Intercept(interceptors ...Interceptor) {
	c.inters.DontStarveAdmin = append(c.inters.DontStarveAdmin, interceptors...)
}

// Create returns a builder for creating a DontStarveAdmin entity.
func (c *DontStarveAdminClient) Create() *DontStarveAdminCreate {
	mutation := newDontStarveAdminMutation(c.config, OpCreate)
	return &DontStarveAdminCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DontStarveAdmin entities.
func (c *DontStarveAdminClient) CreateBulk(builders ...*DontStarveAdminCreate) *DontStarveAdminCreateBulk {
	return &DontStarveAdminCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DontStarveAdminClient) MapCreateBulk(slice any, setFunc func(*DontStarveAdminCreate, int)) *DontStarveAdminCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DontStarveAdminCreateBulk{err: fmt.Errorf("calling to DontStarveAdminClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DontStarveAdminCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DontStarveAdminCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DontStarveAdmin.
func (c *DontStarveAdminClient) Update() *DontStarveAdminUpdate {
	mutation := newDontStarveAdminMutation(c.config, OpUpdate)
	return &DontStarveAdminUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DontStarveAdminClient) UpdateOne(_m *DontStarveAdmin) *DontStarveAdminUpdateOne {
	mutation := newDontStarveAdminMutation(c.config, OpUpdateOne, withDontStarveAdmin(_m))
	return &DontStarveAdminUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DontStarveAdminClient) UpdateOneID(id string) *DontStarveAdminUpdateOne {
	mutation := newDontStarveAdminMutation(c.config, OpUpdateOne, withDontStarveAdminID(id))
	return &DontStarveAdminUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DontStarveAdmin.
func (c *DontStarveAdminClient) Delete() *DontStarveAdminDelete {
	mutation := newDontStarveAdminMutation(c.config, OpDelete)
	return &DontStarveAdminDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DontStarveAdminClient) DeleteOne(_m *DontStarveAdmin) *DontStarveAdminDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DontStarveAdminClient) DeleteOneID(id string) *DontStarveAdminDeleteOne {
	builder := c.Delete().Where(dontstarveadmin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DontStarveAdminDeleteOne{builder}
}

// Query returns a query builder for DontStarveAdmin.
func (c *DontStarveAdminClient) Query() *DontStarveAdminQuery {
	return &DontStarveAdminQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDontStarveAdmin},
		inters: c.Interceptors(),
	}
}

// Get returns a DontStarveAdmin entity by its id.
func (c *DontStarveAdminClient) Get(ctx context.Context, id string) (*DontStarveAdmin, error) {
	return c.Query().Where(dontstarveadmin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DontStarveAdminClient) GetX(ctx context.Context, id string) *DontStarveAdmin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DontStarveAdminClient) Hooks() []Hook {
	return c.hooks.DontStarveAdmin
}

// Interceptors returns the client interceptors.
func (c *DontStarveAdminClient) Interceptors() []Interceptor {
	return c.inters.DontStarveAdmin
}

func (c *DontStarveAdminClient) mutate(ctx context.Context, m *DontStarveAdminMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DontStarveAdminCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DontStarveAdminUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DontStarveAdminUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DontStarveAdminDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DontStarveAdmin mutation op: %q", m.Op())
	}
}

// DontStarveArchiveClient is a client for the DontStarveArchive schema.
type DontStarveArchiveClient struct {
	config
}

// NewDontStarveArchiveClient returns a client for the DontStarveArchive from the given config.
func NewDontStarveArchiveClient(c config) *DontStarveArchiveClient {
	return &DontStarveArchiveClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dontstarvearchive.Hooks(f(g(h())))`.
func (c *DontStarveArchiveClient) Use(hooks ...Hook) {
	c.hooks.DontStarveArchive = append(c.hooks.DontStarveArchive, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dontstarvearchive.Intercept(f(g(h())))`.
func (c *DontStarveArchiveClient) Intercept(interceptors ...Interceptor) {
	c.inters.DontStarveArchive = append(c.inters.DontStarveArchive, interceptors...)
}

// Create returns a builder for creating a DontStarveArchive entity.
func (c *DontStarveArchiveClient) Create() *DontStarveArchiveCreate {
	mutation := newDontStarveArchiveMutation(c.config, OpCreate)
	return &DontStarveArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DontStarveArchive entities.
func (c *DontStarveArchiveClient) CreateBulk(builders ...*DontStarveArchiveCreate) *DontStarveArchiveCreateBulk {
	return &DontStarveArchiveCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DontStarveArchiveClient) MapCreateBulk(slice any, setFunc func(*DontStarveArchiveCreate, int)) *DontStarveArchiveCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DontStarveArchiveCreateBulk{err: fmt.Errorf("calling to DontStarveArchiveClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DontStarveArchiveCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DontStarveArchiveCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DontStarveArchive.
func (c *DontStarveArchiveClient) Update() *DontStarveArchiveUpdate {
	mutation := newDontStarveArchiveMutation(c.config, OpUpdate)
	return &DontStarveArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DontStarveArchiveClient) UpdateOne(_m *DontStarveArchive) *DontStarveArchiveUpdateOne {
	mutation := newDontStarveArchiveMutation(c.config, OpUpdateOne, withDontStarveArchive(_m))
	return &DontStarveArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DontStarveArchiveClient) UpdateOneID(id string) *DontStarveArchiveUpdateOne {
	mutation := newDontStarveArchiveMutation(c.config, OpUpdateOne, withDontStarveArchiveID(id))
	return &DontStarveArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DontStarveArchive.
func (c *DontStarveArchiveClient) Delete() *DontStarveArchiveDelete {
	mutation := newDontStarveArchiveMutation(c.config, OpDelete)
	return &DontStarveArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DontStarveArchiveClient) DeleteOne(_m *DontStarveArchive) *DontStarveArchiveDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DontStarveArchiveClient) DeleteOneID(id string) *DontStarveArchiveDeleteOne {
	builder := c.Delete().Where(dontstarvearchive.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DontStarveArchiveDeleteOne{builder}
}

// Query returns a query builder for DontStarveArchive.
func (c *DontStarveArchiveClient) Query() *DontStarveArchiveQuery {
	return &DontStarveArchiveQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDontStarveArchive},
		inters: c.Interceptors(),
	}
}

// Get returns a DontStarveArchive entity by its id.
func (c *DontStarveArchiveClient) Get(ctx context.Context, id string) (*DontStarveArchive, error) {
	return c.Query().Where(dontstarvearchive.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DontStarveArchiveClient) GetX(ctx context.Context, id string) *DontStarveArchive {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMods queries the mods edge of a DontStarveArchive.
func (c *DontStarveArchiveClient) QueryMods(_m *DontStarveArchive) *DontStarveModQuery {
	query := (&DontStarveModClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dontstarvearchive.Table, dontstarvearchive.FieldID, id),
			sqlgraph.To(dontstarvemod.Table, dontstarvemod.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dontstarvearchive.ModsTable, dontstarvearchive.ModsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DontStarveArchiveClient) Hooks() []Hook {
	return c.hooks.DontStarveArchive
}

// Interceptors returns the client interceptors.
func (c *DontStarveArchiveClient) Interceptors() []Interceptor {
	return c.inters.DontStarveArchive
}

func (c *DontStarveArchiveClient) mutate(ctx context.Context, m *DontStarveArchiveMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DontStarveArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DontStarveArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DontStarveArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DontStarveArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DontStarveArchive mutation op: %q", m.Op())
	}
}

// DontStarveModClient is a client for the DontStarveMod schema.
type DontStarveModClient struct {
	config
}

// NewDontStarveModClient returns a client for the DontStarveMod from the given config.
func NewDontStarveModClient(c config) *DontStarveModClient {
	return &DontStarveModClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dontstarvemod.Hooks(f(g(h())))`.
func (c *DontStarveModClient) Use(hooks ...Hook) {
	c.hooks.DontStarveMod = append(c.hooks.DontStarveMod, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dontstarvemod.Intercept(f(g(h())))`.
func (c *DontStarveModClient) Intercept(interceptors ...Interceptor) {
	c.inters.DontStarveMod = append(c.inters.DontStarveMod, interceptors...)
}

// Create returns a builder for creating a DontStarveMod entity.
func (c *DontStarveModClient) Create() *DontStarveModCreate {
	mutation := newDontStarveModMutation(c.config, OpCreate)
	return &DontStarveModCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DontStarveMod entities.
func (c *DontStarveModClient) CreateBulk(builders ...*DontStarveModCreate) *DontStarveModCreateBulk {
	return &DontStarveModCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DontStarveModClient) MapCreateBulk(slice any, setFunc func(*DontStarveModCreate, int)) *DontStarveModCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DontStarveModCreateBulk{err: fmt.Errorf("calling to DontStarveModClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DontStarveModCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DontStarveModCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DontStarveMod.
func (c *DontStarveModClient) Update() *DontStarveModUpdate {
	mutation := newDontStarveModMutation(c.config, OpUpdate)
	return &DontStarveModUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DontStarveModClient) UpdateOne(_m *DontStarveMod) *DontStarveModUpdateOne {
	mutation := newDontStarveModMutation(c.config, OpUpdateOne, withDontStarveMod(_m))
	return &DontStarveModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DontStarveModClient) UpdateOneID(id string) *DontStarveModUpdateOne {
	mutation := newDontStarveModMutation(c.config, OpUpdateOne, withDontStarveModID(id))
	return &DontStarveModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DontStarveMod.
func (c *DontStarveModClient) Delete() *DontStarveModDelete {
	mutation := newDontStarveModMutation(c.config, OpDelete)
	return &DontStarveModDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DontStarveModClient) DeleteOne(_m *DontStarveMod) *DontStarveModDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DontStarveModClient) DeleteOneID(id string) *DontStarveModDeleteOne {
	builder := c.Delete().Where(dontstarvemod.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DontStarveModDeleteOne{builder}
}

// Query returns a query builder for DontStarveMod.
func (c *DontStarveModClient) Query() *DontStarveModQuery {
	return &DontStarveModQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDontStarveMod},
		inters: c.Interceptors(),
	}
}

// Get returns a DontStarveMod entity by its id.
func (c *DontStarveModClient) Get(ctx context.Context, id string) (*DontStarveMod, error) {
	return c.Query().Where(dontstarvemod.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DontStarveModClient) GetX(ctx context.Context, id string) *DontStarveMod {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArchives queries the archives edge of a DontStarveMod.
func (c *DontStarveModClient) QueryArchives(_m *DontStarveMod) *DontStarveArchiveQuery {
	query := (&DontStarveArchiveClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dontstarvemod.Table, dontstarvemod.FieldID, id),
			sqlgraph.To(dontstarvearchive.Table, dontstarvearchive.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, dontstarvemod.ArchivesTable, dontstarvemod.ArchivesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DontStarveModClient) Hooks() []Hook {
	return c.hooks.DontStarveMod
}

// Interceptors returns the client interceptors.
func (c *DontStarveModClient) Interceptors() []Interceptor {
	return c.inters.DontStarveMod
}

func (c *DontStarveModClient) mutate(ctx context.Context, m *DontStarveModMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DontStarveModCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DontStarveModUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DontStarveModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DontStarveModDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DontStarveMod mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DontStarveAdmin, DontStarveArchive, DontStarveMod []ent.Hook
	}
	inters struct {
		DontStarveAdmin, DontStarveArchive, DontStarveMod []ent.Interceptor
	}
)
