// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/ent/predicate"
	"aurora-admin/internal/entity/dstety"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// DontStarveArchiveUpdate is the builder for updating DontStarveArchive entities.
type DontStarveArchiveUpdate struct {
	config
	hooks    []Hook
	mutation *DontStarveArchiveMutation
}

// Where appends a list predicates to the DontStarveArchiveUpdate builder.
func (_u *DontStarveArchiveUpdate) Where(ps ...predicate.DontStarveArchive) *DontStarveArchiveUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveArchiveUpdate) SetCreatedAt(v time.Time) *DontStarveArchiveUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableCreatedAt(v *time.Time) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveArchiveUpdate) SetUpdatedAt(v time.Time) *DontStarveArchiveUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DontStarveArchiveUpdate) SetRemark(v string) *DontStarveArchiveUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableRemark(v *string) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DontStarveArchiveUpdate) ClearRemark() *DontStarveArchiveUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetClusterName sets the "cluster_name" field.
func (_u *DontStarveArchiveUpdate) SetClusterName(v string) *DontStarveArchiveUpdate {
	_u.mutation.SetClusterName(v)
	return _u
}

// SetNillableClusterName sets the "cluster_name" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableClusterName(v *string) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetClusterName(*v)
	}
	return _u
}

// ClearClusterName clears the value of the "cluster_name" field.
func (_u *DontStarveArchiveUpdate) ClearClusterName() *DontStarveArchiveUpdate {
	_u.mutation.ClearClusterName()
	return _u
}

// SetClusterPassword sets the "cluster_password" field.
func (_u *DontStarveArchiveUpdate) SetClusterPassword(v string) *DontStarveArchiveUpdate {
	_u.mutation.SetClusterPassword(v)
	return _u
}

// SetNillableClusterPassword sets the "cluster_password" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableClusterPassword(v *string) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetClusterPassword(*v)
	}
	return _u
}

// ClearClusterPassword clears the value of the "cluster_password" field.
func (_u *DontStarveArchiveUpdate) ClearClusterPassword() *DontStarveArchiveUpdate {
	_u.mutation.ClearClusterPassword()
	return _u
}

// SetClusterDescription sets the "cluster_description" field.
func (_u *DontStarveArchiveUpdate) SetClusterDescription(v string) *DontStarveArchiveUpdate {
	_u.mutation.SetClusterDescription(v)
	return _u
}

// SetNillableClusterDescription sets the "cluster_description" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableClusterDescription(v *string) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetClusterDescription(*v)
	}
	return _u
}

// ClearClusterDescription clears the value of the "cluster_description" field.
func (_u *DontStarveArchiveUpdate) ClearClusterDescription() *DontStarveArchiveUpdate {
	_u.mutation.ClearClusterDescription()
	return _u
}

// SetMaxPlayers sets the "max_players" field.
func (_u *DontStarveArchiveUpdate) SetMaxPlayers(v int) *DontStarveArchiveUpdate {
	_u.mutation.ResetMaxPlayers()
	_u.mutation.SetMaxPlayers(v)
	return _u
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillableMaxPlayers(v *int) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetMaxPlayers(*v)
	}
	return _u
}

// AddMaxPlayers adds value to the "max_players" field.
func (_u *DontStarveArchiveUpdate) AddMaxPlayers(v int) *DontStarveArchiveUpdate {
	_u.mutation.AddMaxPlayers(v)
	return _u
}

// ClearMaxPlayers clears the value of the "max_players" field.
func (_u *DontStarveArchiveUpdate) ClearMaxPlayers() *DontStarveArchiveUpdate {
	_u.mutation.ClearMaxPlayers()
	return _u
}

// SetPvp sets the "pvp" field.
func (_u *DontStarveArchiveUpdate) SetPvp(v bool) *DontStarveArchiveUpdate {
	_u.mutation.SetPvp(v)
	return _u
}

// SetNillablePvp sets the "pvp" field if the given value is not nil.
func (_u *DontStarveArchiveUpdate) SetNillablePvp(v *bool) *DontStarveArchiveUpdate {
	if v != nil {
		_u.SetPvp(*v)
	}
	return _u
}

// ClearPvp clears the value of the "pvp" field.
func (_u *DontStarveArchiveUpdate) ClearPvp() *DontStarveArchiveUpdate {
	_u.mutation.ClearPvp()
	return _u
}

// SetWorld sets the "world" field.
func (_u *DontStarveArchiveUpdate) SetWorld(v []dstety.DontStarveWorld) *DontStarveArchiveUpdate {
	_u.mutation.SetWorld(v)
	return _u
}

// AppendWorld appends value to the "world" field.
func (_u *DontStarveArchiveUpdate) AppendWorld(v []dstety.DontStarveWorld) *DontStarveArchiveUpdate {
	_u.mutation.AppendWorld(v)
	return _u
}

// ClearWorld clears the value of the "world" field.
func (_u *DontStarveArchiveUpdate) ClearWorld() *DontStarveArchiveUpdate {
	_u.mutation.ClearWorld()
	return _u
}

// AddModIDs adds the "mods" edge to the DontStarveMod entity by IDs.
func (_u *DontStarveArchiveUpdate) AddModIDs(ids ...string) *DontStarveArchiveUpdate {
	_u.mutation.AddModIDs(ids...)
	return _u
}

// AddMods adds the "mods" edges to the DontStarveMod entity.
func (_u *DontStarveArchiveUpdate) AddMods(v ...*DontStarveMod) *DontStarveArchiveUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModIDs(ids...)
}

// Mutation returns the DontStarveArchiveMutation object of the builder.
func (_u *DontStarveArchiveUpdate) Mutation() *DontStarveArchiveMutation {
	return _u.mutation
}

// ClearMods clears all "mods" edges to the DontStarveMod entity.
func (_u *DontStarveArchiveUpdate) ClearMods() *DontStarveArchiveUpdate {
	_u.mutation.ClearMods()
	return _u
}

// RemoveModIDs removes the "mods" edge to DontStarveMod entities by IDs.
func (_u *DontStarveArchiveUpdate) RemoveModIDs(ids ...string) *DontStarveArchiveUpdate {
	_u.mutation.RemoveModIDs(ids...)
	return _u
}

// RemoveMods removes "mods" edges to DontStarveMod entities.
func (_u *DontStarveArchiveUpdate) RemoveMods(v ...*DontStarveMod) *DontStarveArchiveUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DontStarveArchiveUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveArchiveUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DontStarveArchiveUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveArchiveUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveArchiveUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarvearchive.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveArchiveUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarvearchive.Table, dontstarvearchive.Columns, sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dontstarvearchive.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dontstarvearchive.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterName(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterName, field.TypeString, value)
	}
	if _u.mutation.ClusterNameCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterName, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterPassword(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterPassword, field.TypeString, value)
	}
	if _u.mutation.ClusterPasswordCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterPassword, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterDescription(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterDescription, field.TypeString, value)
	}
	if _u.mutation.ClusterDescriptionCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MaxPlayers(); ok {
		_spec.SetField(dontstarvearchive.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPlayers(); ok {
		_spec.AddField(dontstarvearchive.FieldMaxPlayers, field.TypeInt, value)
	}
	if _u.mutation.MaxPlayersCleared() {
		_spec.ClearField(dontstarvearchive.FieldMaxPlayers, field.TypeInt)
	}
	if value, ok := _u.mutation.Pvp(); ok {
		_spec.SetField(dontstarvearchive.FieldPvp, field.TypeBool, value)
	}
	if _u.mutation.PvpCleared() {
		_spec.ClearField(dontstarvearchive.FieldPvp, field.TypeBool)
	}
	if value, ok := _u.mutation.World(); ok {
		_spec.SetField(dontstarvearchive.FieldWorld, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWorld(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dontstarvearchive.FieldWorld, value)
		})
	}
	if _u.mutation.WorldCleared() {
		_spec.ClearField(dontstarvearchive.FieldWorld, field.TypeJSON)
	}
	if _u.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModsIDs(); len(nodes) > 0 && !_u.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarvearchive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DontStarveArchiveUpdateOne is the builder for updating a single DontStarveArchive entity.
type DontStarveArchiveUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DontStarveArchiveMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveArchiveUpdateOne) SetCreatedAt(v time.Time) *DontStarveArchiveUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableCreatedAt(v *time.Time) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveArchiveUpdateOne) SetUpdatedAt(v time.Time) *DontStarveArchiveUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DontStarveArchiveUpdateOne) SetRemark(v string) *DontStarveArchiveUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableRemark(v *string) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DontStarveArchiveUpdateOne) ClearRemark() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetClusterName sets the "cluster_name" field.
func (_u *DontStarveArchiveUpdateOne) SetClusterName(v string) *DontStarveArchiveUpdateOne {
	_u.mutation.SetClusterName(v)
	return _u
}

// SetNillableClusterName sets the "cluster_name" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableClusterName(v *string) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetClusterName(*v)
	}
	return _u
}

// ClearClusterName clears the value of the "cluster_name" field.
func (_u *DontStarveArchiveUpdateOne) ClearClusterName() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearClusterName()
	return _u
}

// SetClusterPassword sets the "cluster_password" field.
func (_u *DontStarveArchiveUpdateOne) SetClusterPassword(v string) *DontStarveArchiveUpdateOne {
	_u.mutation.SetClusterPassword(v)
	return _u
}

// SetNillableClusterPassword sets the "cluster_password" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableClusterPassword(v *string) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetClusterPassword(*v)
	}
	return _u
}

// ClearClusterPassword clears the value of the "cluster_password" field.
func (_u *DontStarveArchiveUpdateOne) ClearClusterPassword() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearClusterPassword()
	return _u
}

// SetClusterDescription sets the "cluster_description" field.
func (_u *DontStarveArchiveUpdateOne) SetClusterDescription(v string) *DontStarveArchiveUpdateOne {
	_u.mutation.SetClusterDescription(v)
	return _u
}

// SetNillableClusterDescription sets the "cluster_description" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableClusterDescription(v *string) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetClusterDescription(*v)
	}
	return _u
}

// ClearClusterDescription clears the value of the "cluster_description" field.
func (_u *DontStarveArchiveUpdateOne) ClearClusterDescription() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearClusterDescription()
	return _u
}

// SetMaxPlayers sets the "max_players" field.
func (_u *DontStarveArchiveUpdateOne) SetMaxPlayers(v int) *DontStarveArchiveUpdateOne {
	_u.mutation.ResetMaxPlayers()
	_u.mutation.SetMaxPlayers(v)
	return _u
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillableMaxPlayers(v *int) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetMaxPlayers(*v)
	}
	return _u
}

// AddMaxPlayers adds value to the "max_players" field.
func (_u *DontStarveArchiveUpdateOne) AddMaxPlayers(v int) *DontStarveArchiveUpdateOne {
	_u.mutation.AddMaxPlayers(v)
	return _u
}

// ClearMaxPlayers clears the value of the "max_players" field.
func (_u *DontStarveArchiveUpdateOne) ClearMaxPlayers() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearMaxPlayers()
	return _u
}

// SetPvp sets the "pvp" field.
func (_u *DontStarveArchiveUpdateOne) SetPvp(v bool) *DontStarveArchiveUpdateOne {
	_u.mutation.SetPvp(v)
	return _u
}

// SetNillablePvp sets the "pvp" field if the given value is not nil.
func (_u *DontStarveArchiveUpdateOne) SetNillablePvp(v *bool) *DontStarveArchiveUpdateOne {
	if v != nil {
		_u.SetPvp(*v)
	}
	return _u
}

// ClearPvp clears the value of the "pvp" field.
func (_u *DontStarveArchiveUpdateOne) ClearPvp() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearPvp()
	return _u
}

// SetWorld sets the "world" field.
func (_u *DontStarveArchiveUpdateOne) SetWorld(v []dstety.DontStarveWorld) *DontStarveArchiveUpdateOne {
	_u.mutation.SetWorld(v)
	return _u
}

// AppendWorld appends value to the "world" field.
func (_u *DontStarveArchiveUpdateOne) AppendWorld(v []dstety.DontStarveWorld) *DontStarveArchiveUpdateOne {
	_u.mutation.AppendWorld(v)
	return _u
}

// ClearWorld clears the value of the "world" field.
func (_u *DontStarveArchiveUpdateOne) ClearWorld() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearWorld()
	return _u
}

// AddModIDs adds the "mods" edge to the DontStarveMod entity by IDs.
func (_u *DontStarveArchiveUpdateOne) AddModIDs(ids ...string) *DontStarveArchiveUpdateOne {
	_u.mutation.AddModIDs(ids...)
	return _u
}

// AddMods adds the "mods" edges to the DontStarveMod entity.
func (_u *DontStarveArchiveUpdateOne) AddMods(v ...*DontStarveMod) *DontStarveArchiveUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModIDs(ids...)
}

// Mutation returns the DontStarveArchiveMutation object of the builder.
func (_u *DontStarveArchiveUpdateOne) Mutation() *DontStarveArchiveMutation {
	return _u.mutation
}

// ClearMods clears all "mods" edges to the DontStarveMod entity.
func (_u *DontStarveArchiveUpdateOne) ClearMods() *DontStarveArchiveUpdateOne {
	_u.mutation.ClearMods()
	return _u
}

// RemoveModIDs removes the "mods" edge to DontStarveMod entities by IDs.
func (_u *DontStarveArchiveUpdateOne) RemoveModIDs(ids ...string) *DontStarveArchiveUpdateOne {
	_u.mutation.RemoveModIDs(ids...)
	return _u
}

// RemoveMods removes "mods" edges to DontStarveMod entities.
func (_u *DontStarveArchiveUpdateOne) RemoveMods(v ...*DontStarveMod) *DontStarveArchiveUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModIDs(ids...)
}

// Where appends a list predicates to the DontStarveArchiveUpdate builder.
func (_u *DontStarveArchiveUpdateOne) Where(ps ...predicate.DontStarveArchive) *DontStarveArchiveUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DontStarveArchiveUpdateOne) Select(field string, fields ...string) *DontStarveArchiveUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DontStarveArchive entity.
func (_u *DontStarveArchiveUpdateOne) Save(ctx context.Context) (*DontStarveArchive, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveArchiveUpdateOne) SaveX(ctx context.Context) *DontStarveArchive {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DontStarveArchiveUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveArchiveUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveArchiveUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarvearchive.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveArchiveUpdateOne) sqlSave(ctx context.Context) (_node *DontStarveArchive, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarvearchive.Table, dontstarvearchive.Columns, sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DontStarveArchive.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dontstarvearchive.FieldID)
		for _, f := range fields {
			if !dontstarvearchive.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dontstarvearchive.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dontstarvearchive.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dontstarvearchive.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterName(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterName, field.TypeString, value)
	}
	if _u.mutation.ClusterNameCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterName, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterPassword(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterPassword, field.TypeString, value)
	}
	if _u.mutation.ClusterPasswordCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterPassword, field.TypeString)
	}
	if value, ok := _u.mutation.ClusterDescription(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterDescription, field.TypeString, value)
	}
	if _u.mutation.ClusterDescriptionCleared() {
		_spec.ClearField(dontstarvearchive.FieldClusterDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MaxPlayers(); ok {
		_spec.SetField(dontstarvearchive.FieldMaxPlayers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPlayers(); ok {
		_spec.AddField(dontstarvearchive.FieldMaxPlayers, field.TypeInt, value)
	}
	if _u.mutation.MaxPlayersCleared() {
		_spec.ClearField(dontstarvearchive.FieldMaxPlayers, field.TypeInt)
	}
	if value, ok := _u.mutation.Pvp(); ok {
		_spec.SetField(dontstarvearchive.FieldPvp, field.TypeBool, value)
	}
	if _u.mutation.PvpCleared() {
		_spec.ClearField(dontstarvearchive.FieldPvp, field.TypeBool)
	}
	if value, ok := _u.mutation.World(); ok {
		_spec.SetField(dontstarvearchive.FieldWorld, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWorld(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dontstarvearchive.FieldWorld, value)
		})
	}
	if _u.mutation.WorldCleared() {
		_spec.ClearField(dontstarvearchive.FieldWorld, field.TypeJSON)
	}
	if _u.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModsIDs(); len(nodes) > 0 && !_u.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DontStarveArchive{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarvearchive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
