// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarveadmin"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveAdminCreate is the builder for creating a DontStarveAdmin entity.
type DontStarveAdminCreate struct {
	config
	mutation *DontStarveAdminMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DontStarveAdminCreate) SetCreatedAt(v time.Time) *DontStarveAdminCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DontStarveAdminCreate) SetNillableCreatedAt(v *time.Time) *DontStarveAdminCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DontStarveAdminCreate) SetUpdatedAt(v time.Time) *DontStarveAdminCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DontStarveAdminCreate) SetNillableUpdatedAt(v *time.Time) *DontStarveAdminCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DontStarveAdminCreate) SetName(v string) *DontStarveAdminCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DontStarveAdminCreate) SetNillableName(v *string) *DontStarveAdminCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetKleiID sets the "klei_id" field.
func (_c *DontStarveAdminCreate) SetKleiID(v string) *DontStarveAdminCreate {
	_c.mutation.SetKleiID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DontStarveAdminCreate) SetID(v string) *DontStarveAdminCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DontStarveAdminCreate) SetNillableID(v *string) *DontStarveAdminCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DontStarveAdminMutation object of the builder.
func (_c *DontStarveAdminCreate) Mutation() *DontStarveAdminMutation {
	return _c.mutation
}

// Save creates the DontStarveAdmin in the database.
func (_c *DontStarveAdminCreate) Save(ctx context.Context) (*DontStarveAdmin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DontStarveAdminCreate) SaveX(ctx context.Context) *DontStarveAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveAdminCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveAdminCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DontStarveAdminCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dontstarveadmin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dontstarveadmin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dontstarveadmin.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DontStarveAdminCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DontStarveAdmin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DontStarveAdmin.updated_at"`)}
	}
	if _, ok := _c.mutation.KleiID(); !ok {
		return &ValidationError{Name: "klei_id", err: errors.New(`ent: missing required field "DontStarveAdmin.klei_id"`)}
	}
	return nil
}

func (_c *DontStarveAdminCreate) sqlSave(ctx context.Context) (*DontStarveAdmin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DontStarveAdmin.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DontStarveAdminCreate) createSpec() (*DontStarveAdmin, *sqlgraph.CreateSpec) {
	var (
		_node = &DontStarveAdmin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dontstarveadmin.Table, sqlgraph.NewFieldSpec(dontstarveadmin.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dontstarveadmin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KleiID(); ok {
		_spec.SetField(dontstarveadmin.FieldKleiID, field.TypeString, value)
		_node.KleiID = value
	}
	return _node, _spec
}

// DontStarveAdminCreateBulk is the builder for creating many DontStarveAdmin entities in bulk.
type DontStarveAdminCreateBulk struct {
	config
	err      error
	builders []*DontStarveAdminCreate
}

// Save creates the DontStarveAdmin entities in the database.
func (_c *DontStarveAdminCreateBulk) Save(ctx context.Context) ([]*DontStarveAdmin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DontStarveAdmin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DontStarveAdminMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DontStarveAdminCreateBulk) SaveX(ctx context.Context) []*DontStarveAdmin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveAdminCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveAdminCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
