// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarveadmin"
	"aurora-admin/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveAdminUpdate is the builder for updating DontStarveAdmin entities.
type DontStarveAdminUpdate struct {
	config
	hooks    []Hook
	mutation *DontStarveAdminMutation
}

// Where appends a list predicates to the DontStarveAdminUpdate builder.
func (_u *DontStarveAdminUpdate) Where(ps ...predicate.DontStarveAdmin) *DontStarveAdminUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveAdminUpdate) SetCreatedAt(v time.Time) *DontStarveAdminUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveAdminUpdate) SetNillableCreatedAt(v *time.Time) *DontStarveAdminUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveAdminUpdate) SetUpdatedAt(v time.Time) *DontStarveAdminUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DontStarveAdminUpdate) SetName(v string) *DontStarveAdminUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DontStarveAdminUpdate) SetNillableName(v *string) *DontStarveAdminUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DontStarveAdminUpdate) ClearName() *DontStarveAdminUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetKleiID sets the "klei_id" field.
func (_u *DontStarveAdminUpdate) SetKleiID(v string) *DontStarveAdminUpdate {
	_u.mutation.SetKleiID(v)
	return _u
}

// SetNillableKleiID sets the "klei_id" field if the given value is not nil.
func (_u *DontStarveAdminUpdate) SetNillableKleiID(v *string) *DontStarveAdminUpdate {
	if v != nil {
		_u.SetKleiID(*v)
	}
	return _u
}

// Mutation returns the DontStarveAdminMutation object of the builder.
func (_u *DontStarveAdminUpdate) Mutation() *DontStarveAdminMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DontStarveAdminUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveAdminUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DontStarveAdminUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveAdminUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveAdminUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarveadmin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveAdminUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarveadmin.Table, dontstarveadmin.Columns, sqlgraph.NewFieldSpec(dontstarveadmin.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dontstarveadmin.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dontstarveadmin.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.KleiID(); ok {
		_spec.SetField(dontstarveadmin.FieldKleiID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarveadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DontStarveAdminUpdateOne is the builder for updating a single DontStarveAdmin entity.
type DontStarveAdminUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DontStarveAdminMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveAdminUpdateOne) SetCreatedAt(v time.Time) *DontStarveAdminUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveAdminUpdateOne) SetNillableCreatedAt(v *time.Time) *DontStarveAdminUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveAdminUpdateOne) SetUpdatedAt(v time.Time) *DontStarveAdminUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DontStarveAdminUpdateOne) SetName(v string) *DontStarveAdminUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DontStarveAdminUpdateOne) SetNillableName(v *string) *DontStarveAdminUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DontStarveAdminUpdateOne) ClearName() *DontStarveAdminUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetKleiID sets the "klei_id" field.
func (_u *DontStarveAdminUpdateOne) SetKleiID(v string) *DontStarveAdminUpdateOne {
	_u.mutation.SetKleiID(v)
	return _u
}

// SetNillableKleiID sets the "klei_id" field if the given value is not nil.
func (_u *DontStarveAdminUpdateOne) SetNillableKleiID(v *string) *DontStarveAdminUpdateOne {
	if v != nil {
		_u.SetKleiID(*v)
	}
	return _u
}

// Mutation returns the DontStarveAdminMutation object of the builder.
func (_u *DontStarveAdminUpdateOne) Mutation() *DontStarveAdminMutation {
	return _u.mutation
}

// Where appends a list predicates to the DontStarveAdminUpdate builder.
func (_u *DontStarveAdminUpdateOne) Where(ps ...predicate.DontStarveAdmin) *DontStarveAdminUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DontStarveAdminUpdateOne) Select(field string, fields ...string) *DontStarveAdminUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DontStarveAdmin entity.
func (_u *DontStarveAdminUpdateOne) Save(ctx context.Context) (*DontStarveAdmin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveAdminUpdateOne) SaveX(ctx context.Context) *DontStarveAdmin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DontStarveAdminUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveAdminUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveAdminUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarveadmin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveAdminUpdateOne) sqlSave(ctx context.Context) (_node *DontStarveAdmin, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarveadmin.Table, dontstarveadmin.Columns, sqlgraph.NewFieldSpec(dontstarveadmin.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DontStarveAdmin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dontstarveadmin.FieldID)
		for _, f := range fields {
			if !dontstarveadmin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dontstarveadmin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarveadmin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dontstarveadmin.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dontstarveadmin.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.KleiID(); ok {
		_spec.SetField(dontstarveadmin.FieldKleiID, field.TypeString, value)
	}
	_node = &DontStarveAdmin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarveadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
