// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/internal/entity/dstety"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DontStarveArchive is the model entity for the DontStarveArchive schema.
type DontStarveArchive struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// ClusterName holds the value of the "cluster_name" field.
	ClusterName string `json:"cluster_name,omitempty"`
	// ClusterPassword holds the value of the "cluster_password" field.
	ClusterPassword string `json:"cluster_password,omitempty"`
	// ClusterDescription holds the value of the "cluster_description" field.
	ClusterDescription string `json:"cluster_description,omitempty"`
	// MaxPlayers holds the value of the "max_players" field.
	MaxPlayers int `json:"max_players,omitempty"`
	// Pvp holds the value of the "pvp" field.
	Pvp bool `json:"pvp,omitempty"`
	// World holds the value of the "world" field.
	World []dstety.DontStarveWorld `json:"world,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DontStarveArchiveQuery when eager-loading is set.
	Edges        DontStarveArchiveEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DontStarveArchiveEdges holds the relations/edges for other nodes in the graph.
type DontStarveArchiveEdges struct {
	// Mods holds the value of the mods edge.
	Mods []*DontStarveMod `json:"mods,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModsOrErr returns the Mods value or an error if the edge
// was not loaded in eager-loading.
func (e DontStarveArchiveEdges) ModsOrErr() ([]*DontStarveMod, error) {
	if e.loadedTypes[0] {
		return e.Mods, nil
	}
	return nil, &NotLoadedError{edge: "mods"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DontStarveArchive) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dontstarvearchive.FieldWorld:
			values[i] = new([]byte)
		case dontstarvearchive.FieldPvp:
			values[i] = new(sql.NullBool)
		case dontstarvearchive.FieldMaxPlayers:
			values[i] = new(sql.NullInt64)
		case dontstarvearchive.FieldID, dontstarvearchive.FieldRemark, dontstarvearchive.FieldClusterName, dontstarvearchive.FieldClusterPassword, dontstarvearchive.FieldClusterDescription:
			values[i] = new(sql.NullString)
		case dontstarvearchive.FieldCreatedAt, dontstarvearchive.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DontStarveArchive fields.
func (_m *DontStarveArchive) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dontstarvearchive.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case dontstarvearchive.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dontstarvearchive.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dontstarvearchive.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case dontstarvearchive.FieldClusterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_name", values[i])
			} else if value.Valid {
				_m.ClusterName = value.String
			}
		case dontstarvearchive.FieldClusterPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_password", values[i])
			} else if value.Valid {
				_m.ClusterPassword = value.String
			}
		case dontstarvearchive.FieldClusterDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_description", values[i])
			} else if value.Valid {
				_m.ClusterDescription = value.String
			}
		case dontstarvearchive.FieldMaxPlayers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_players", values[i])
			} else if value.Valid {
				_m.MaxPlayers = int(value.Int64)
			}
		case dontstarvearchive.FieldPvp:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pvp", values[i])
			} else if value.Valid {
				_m.Pvp = value.Bool
			}
		case dontstarvearchive.FieldWorld:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field world", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.World); err != nil {
					return fmt.Errorf("unmarshal field world: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DontStarveArchive.
// This includes values selected through modifiers, order, etc.
func (_m *DontStarveArchive) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMods queries the "mods" edge of the DontStarveArchive entity.
func (_m *DontStarveArchive) QueryMods() *DontStarveModQuery {
	return NewDontStarveArchiveClient(_m.config).QueryMods(_m)
}

// Update returns a builder for updating this DontStarveArchive.
// Note that you need to call DontStarveArchive.Unwrap() before calling this method if this DontStarveArchive
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DontStarveArchive) Update() *DontStarveArchiveUpdateOne {
	return NewDontStarveArchiveClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DontStarveArchive entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DontStarveArchive) Unwrap() *DontStarveArchive {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DontStarveArchive is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DontStarveArchive) String() string {
	var builder strings.Builder
	builder.WriteString("DontStarveArchive(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("cluster_name=")
	builder.WriteString(_m.ClusterName)
	builder.WriteString(", ")
	builder.WriteString("cluster_password=")
	builder.WriteString(_m.ClusterPassword)
	builder.WriteString(", ")
	builder.WriteString("cluster_description=")
	builder.WriteString(_m.ClusterDescription)
	builder.WriteString(", ")
	builder.WriteString("max_players=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPlayers))
	builder.WriteString(", ")
	builder.WriteString("pvp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pvp))
	builder.WriteString(", ")
	builder.WriteString("world=")
	builder.WriteString(fmt.Sprintf("%v", _m.World))
	builder.WriteByte(')')
	return builder.String()
}

// DontStarveArchives is a parsable slice of DontStarveArchive.
type DontStarveArchives []*DontStarveArchive
