// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveArchiveDelete is the builder for deleting a DontStarveArchive entity.
type DontStarveArchiveDelete struct {
	config
	hooks    []Hook
	mutation *DontStarveArchiveMutation
}

// Where appends a list predicates to the DontStarveArchiveDelete builder.
func (_d *DontStarveArchiveDelete) Where(ps ...predicate.DontStarveArchive) *DontStarveArchiveDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DontStarveArchiveDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DontStarveArchiveDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DontStarveArchiveDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dontstarvearchive.Table, sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DontStarveArchiveDeleteOne is the builder for deleting a single DontStarveArchive entity.
type DontStarveArchiveDeleteOne struct {
	_d *DontStarveArchiveDelete
}

// Where appends a list predicates to the DontStarveArchiveDelete builder.
func (_d *DontStarveArchiveDeleteOne) Where(ps ...predicate.DontStarveArchive) *DontStarveArchiveDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DontStarveArchiveDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dontstarvearchive.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DontStarveArchiveDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
