// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/internal/entity/dstety"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveModCreate is the builder for creating a DontStarveMod entity.
type DontStarveModCreate struct {
	config
	mutation *DontStarveModMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DontStarveModCreate) SetCreatedAt(v time.Time) *DontStarveModCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableCreatedAt(v *time.Time) *DontStarveModCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DontStarveModCreate) SetUpdatedAt(v time.Time) *DontStarveModCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableUpdatedAt(v *time.Time) *DontStarveModCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkshopID sets the "workshop_id" field.
func (_c *DontStarveModCreate) SetWorkshopID(v string) *DontStarveModCreate {
	_c.mutation.SetWorkshopID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DontStarveModCreate) SetName(v string) *DontStarveModCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableName(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTimeCreated sets the "time_created" field.
func (_c *DontStarveModCreate) SetTimeCreated(v int) *DontStarveModCreate {
	_c.mutation.SetTimeCreated(v)
	return _c
}

// SetNillableTimeCreated sets the "time_created" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableTimeCreated(v *int) *DontStarveModCreate {
	if v != nil {
		_c.SetTimeCreated(*v)
	}
	return _c
}

// SetTimeUpdated sets the "time_updated" field.
func (_c *DontStarveModCreate) SetTimeUpdated(v int) *DontStarveModCreate {
	_c.mutation.SetTimeUpdated(v)
	return _c
}

// SetNillableTimeUpdated sets the "time_updated" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableTimeUpdated(v *int) *DontStarveModCreate {
	if v != nil {
		_c.SetTimeUpdated(*v)
	}
	return _c
}

// SetImage sets the "image" field.
func (_c *DontStarveModCreate) SetImage(v string) *DontStarveModCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableImage(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetImage(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *DontStarveModCreate) SetDescription(v string) *DontStarveModCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableDescription(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *DontStarveModCreate) SetAuthor(v string) *DontStarveModCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableAuthor(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *DontStarveModCreate) SetVersion(v string) *DontStarveModCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableVersion(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDownloaded sets the "downloaded" field.
func (_c *DontStarveModCreate) SetDownloaded(v bool) *DontStarveModCreate {
	_c.mutation.SetDownloaded(v)
	return _c
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableDownloaded(v *bool) *DontStarveModCreate {
	if v != nil {
		_c.SetDownloaded(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *DontStarveModCreate) SetConfig(v []dstety.DontStarveModConfig) *DontStarveModCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetRawConfig sets the "raw_config" field.
func (_c *DontStarveModCreate) SetRawConfig(v string) *DontStarveModCreate {
	_c.mutation.SetRawConfig(v)
	return _c
}

// SetNillableRawConfig sets the "raw_config" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableRawConfig(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetRawConfig(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DontStarveModCreate) SetID(v string) *DontStarveModCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DontStarveModCreate) SetNillableID(v *string) *DontStarveModCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddArchiveIDs adds the "archives" edge to the DontStarveArchive entity by IDs.
func (_c *DontStarveModCreate) AddArchiveIDs(ids ...string) *DontStarveModCreate {
	_c.mutation.AddArchiveIDs(ids...)
	return _c
}

// AddArchives adds the "archives" edges to the DontStarveArchive entity.
func (_c *DontStarveModCreate) AddArchives(v ...*DontStarveArchive) *DontStarveModCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchiveIDs(ids...)
}

// Mutation returns the DontStarveModMutation object of the builder.
func (_c *DontStarveModCreate) Mutation() *DontStarveModMutation {
	return _c.mutation
}

// Save creates the DontStarveMod in the database.
func (_c *DontStarveModCreate) Save(ctx context.Context) (*DontStarveMod, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DontStarveModCreate) SaveX(ctx context.Context) *DontStarveMod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveModCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveModCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DontStarveModCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dontstarvemod.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dontstarvemod.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dontstarvemod.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DontStarveModCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DontStarveMod.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DontStarveMod.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkshopID(); !ok {
		return &ValidationError{Name: "workshop_id", err: errors.New(`ent: missing required field "DontStarveMod.workshop_id"`)}
	}
	return nil
}

func (_c *DontStarveModCreate) sqlSave(ctx context.Context) (*DontStarveMod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DontStarveMod.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DontStarveModCreate) createSpec() (*DontStarveMod, *sqlgraph.CreateSpec) {
	var (
		_node = &DontStarveMod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dontstarvemod.Table, sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkshopID(); ok {
		_spec.SetField(dontstarvemod.FieldWorkshopID, field.TypeString, value)
		_node.WorkshopID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dontstarvemod.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TimeCreated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeCreated, field.TypeInt, value)
		_node.TimeCreated = value
	}
	if value, ok := _c.mutation.TimeUpdated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeUpdated, field.TypeInt, value)
		_node.TimeUpdated = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(dontstarvemod.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(dontstarvemod.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(dontstarvemod.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(dontstarvemod.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Downloaded(); ok {
		_spec.SetField(dontstarvemod.FieldDownloaded, field.TypeBool, value)
		_node.Downloaded = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(dontstarvemod.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.RawConfig(); ok {
		_spec.SetField(dontstarvemod.FieldRawConfig, field.TypeString, value)
		_node.RawConfig = value
	}
	if nodes := _c.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DontStarveModCreateBulk is the builder for creating many DontStarveMod entities in bulk.
type DontStarveModCreateBulk struct {
	config
	err      error
	builders []*DontStarveModCreate
}

// Save creates the DontStarveMod entities in the database.
func (_c *DontStarveModCreateBulk) Save(ctx context.Context) ([]*DontStarveMod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DontStarveMod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DontStarveModMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DontStarveModCreateBulk) SaveX(ctx context.Context) []*DontStarveMod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveModCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveModCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
