// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarveadmin"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DontStarveAdmin is the model entity for the DontStarveAdmin schema.
type DontStarveAdmin struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// KleiID holds the value of the "klei_id" field.
	KleiID       string `json:"klei_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DontStarveAdmin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dontstarveadmin.FieldID, dontstarveadmin.FieldName, dontstarveadmin.FieldKleiID:
			values[i] = new(sql.NullString)
		case dontstarveadmin.FieldCreatedAt, dontstarveadmin.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DontStarveAdmin fields.
func (_m *DontStarveAdmin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dontstarveadmin.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case dontstarveadmin.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dontstarveadmin.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dontstarveadmin.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case dontstarveadmin.FieldKleiID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field klei_id", values[i])
			} else if value.Valid {
				_m.KleiID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DontStarveAdmin.
// This includes values selected through modifiers, order, etc.
func (_m *DontStarveAdmin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DontStarveAdmin.
// Note that you need to call DontStarveAdmin.Unwrap() before calling this method if this DontStarveAdmin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DontStarveAdmin) Update() *DontStarveAdminUpdateOne {
	return NewDontStarveAdminClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DontStarveAdmin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DontStarveAdmin) Unwrap() *DontStarveAdmin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DontStarveAdmin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DontStarveAdmin) String() string {
	var builder strings.Builder
	builder.WriteString("DontStarveAdmin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("klei_id=")
	builder.WriteString(_m.KleiID)
	builder.WriteByte(')')
	return builder.String()
}

// DontStarveAdmins is a parsable slice of DontStarveAdmin.
type DontStarveAdmins []*DontStarveAdmin
