// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/ent/predicate"
	"aurora-admin/internal/entity/dstety"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// DontStarveModUpdate is the builder for updating DontStarveMod entities.
type DontStarveModUpdate struct {
	config
	hooks    []Hook
	mutation *DontStarveModMutation
}

// Where appends a list predicates to the DontStarveModUpdate builder.
func (_u *DontStarveModUpdate) Where(ps ...predicate.DontStarveMod) *DontStarveModUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveModUpdate) SetCreatedAt(v time.Time) *DontStarveModUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableCreatedAt(v *time.Time) *DontStarveModUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveModUpdate) SetUpdatedAt(v time.Time) *DontStarveModUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkshopID sets the "workshop_id" field.
func (_u *DontStarveModUpdate) SetWorkshopID(v string) *DontStarveModUpdate {
	_u.mutation.SetWorkshopID(v)
	return _u
}

// SetNillableWorkshopID sets the "workshop_id" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableWorkshopID(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetWorkshopID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DontStarveModUpdate) SetName(v string) *DontStarveModUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableName(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DontStarveModUpdate) ClearName() *DontStarveModUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetTimeCreated sets the "time_created" field.
func (_u *DontStarveModUpdate) SetTimeCreated(v int) *DontStarveModUpdate {
	_u.mutation.ResetTimeCreated()
	_u.mutation.SetTimeCreated(v)
	return _u
}

// SetNillableTimeCreated sets the "time_created" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableTimeCreated(v *int) *DontStarveModUpdate {
	if v != nil {
		_u.SetTimeCreated(*v)
	}
	return _u
}

// AddTimeCreated adds value to the "time_created" field.
func (_u *DontStarveModUpdate) AddTimeCreated(v int) *DontStarveModUpdate {
	_u.mutation.AddTimeCreated(v)
	return _u
}

// ClearTimeCreated clears the value of the "time_created" field.
func (_u *DontStarveModUpdate) ClearTimeCreated() *DontStarveModUpdate {
	_u.mutation.ClearTimeCreated()
	return _u
}

// SetTimeUpdated sets the "time_updated" field.
func (_u *DontStarveModUpdate) SetTimeUpdated(v int) *DontStarveModUpdate {
	_u.mutation.ResetTimeUpdated()
	_u.mutation.SetTimeUpdated(v)
	return _u
}

// SetNillableTimeUpdated sets the "time_updated" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableTimeUpdated(v *int) *DontStarveModUpdate {
	if v != nil {
		_u.SetTimeUpdated(*v)
	}
	return _u
}

// AddTimeUpdated adds value to the "time_updated" field.
func (_u *DontStarveModUpdate) AddTimeUpdated(v int) *DontStarveModUpdate {
	_u.mutation.AddTimeUpdated(v)
	return _u
}

// ClearTimeUpdated clears the value of the "time_updated" field.
func (_u *DontStarveModUpdate) ClearTimeUpdated() *DontStarveModUpdate {
	_u.mutation.ClearTimeUpdated()
	return _u
}

// SetImage sets the "image" field.
func (_u *DontStarveModUpdate) SetImage(v string) *DontStarveModUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableImage(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DontStarveModUpdate) ClearImage() *DontStarveModUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DontStarveModUpdate) SetDescription(v string) *DontStarveModUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableDescription(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DontStarveModUpdate) ClearDescription() *DontStarveModUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *DontStarveModUpdate) SetAuthor(v string) *DontStarveModUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableAuthor(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *DontStarveModUpdate) ClearAuthor() *DontStarveModUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetVersion sets the "version" field.
func (_u *DontStarveModUpdate) SetVersion(v string) *DontStarveModUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableVersion(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DontStarveModUpdate) ClearVersion() *DontStarveModUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetDownloaded sets the "downloaded" field.
func (_u *DontStarveModUpdate) SetDownloaded(v bool) *DontStarveModUpdate {
	_u.mutation.SetDownloaded(v)
	return _u
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableDownloaded(v *bool) *DontStarveModUpdate {
	if v != nil {
		_u.SetDownloaded(*v)
	}
	return _u
}

// ClearDownloaded clears the value of the "downloaded" field.
func (_u *DontStarveModUpdate) ClearDownloaded() *DontStarveModUpdate {
	_u.mutation.ClearDownloaded()
	return _u
}

// SetConfig sets the "config" field.
func (_u *DontStarveModUpdate) SetConfig(v []dstety.DontStarveModConfig) *DontStarveModUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *DontStarveModUpdate) AppendConfig(v []dstety.DontStarveModConfig) *DontStarveModUpdate {
	_u.mutation.AppendConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DontStarveModUpdate) ClearConfig() *DontStarveModUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetRawConfig sets the "raw_config" field.
func (_u *DontStarveModUpdate) SetRawConfig(v string) *DontStarveModUpdate {
	_u.mutation.SetRawConfig(v)
	return _u
}

// SetNillableRawConfig sets the "raw_config" field if the given value is not nil.
func (_u *DontStarveModUpdate) SetNillableRawConfig(v *string) *DontStarveModUpdate {
	if v != nil {
		_u.SetRawConfig(*v)
	}
	return _u
}

// ClearRawConfig clears the value of the "raw_config" field.
func (_u *DontStarveModUpdate) ClearRawConfig() *DontStarveModUpdate {
	_u.mutation.ClearRawConfig()
	return _u
}

// AddArchiveIDs adds the "archives" edge to the DontStarveArchive entity by IDs.
func (_u *DontStarveModUpdate) AddArchiveIDs(ids ...string) *DontStarveModUpdate {
	_u.mutation.AddArchiveIDs(ids...)
	return _u
}

// AddArchives adds the "archives" edges to the DontStarveArchive entity.
func (_u *DontStarveModUpdate) AddArchives(v ...*DontStarveArchive) *DontStarveModUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchiveIDs(ids...)
}

// Mutation returns the DontStarveModMutation object of the builder.
func (_u *DontStarveModUpdate) Mutation() *DontStarveModMutation {
	return _u.mutation
}

// ClearArchives clears all "archives" edges to the DontStarveArchive entity.
func (_u *DontStarveModUpdate) ClearArchives() *DontStarveModUpdate {
	_u.mutation.ClearArchives()
	return _u
}

// RemoveArchiveIDs removes the "archives" edge to DontStarveArchive entities by IDs.
func (_u *DontStarveModUpdate) RemoveArchiveIDs(ids ...string) *DontStarveModUpdate {
	_u.mutation.RemoveArchiveIDs(ids...)
	return _u
}

// RemoveArchives removes "archives" edges to DontStarveArchive entities.
func (_u *DontStarveModUpdate) RemoveArchives(v ...*DontStarveArchive) *DontStarveModUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchiveIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DontStarveModUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveModUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DontStarveModUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveModUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveModUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarvemod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveModUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarvemod.Table, dontstarvemod.Columns, sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkshopID(); ok {
		_spec.SetField(dontstarvemod.FieldWorkshopID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dontstarvemod.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dontstarvemod.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.TimeCreated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeCreated(); ok {
		_spec.AddField(dontstarvemod.FieldTimeCreated, field.TypeInt, value)
	}
	if _u.mutation.TimeCreatedCleared() {
		_spec.ClearField(dontstarvemod.FieldTimeCreated, field.TypeInt)
	}
	if value, ok := _u.mutation.TimeUpdated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeUpdated(); ok {
		_spec.AddField(dontstarvemod.FieldTimeUpdated, field.TypeInt, value)
	}
	if _u.mutation.TimeUpdatedCleared() {
		_spec.ClearField(dontstarvemod.FieldTimeUpdated, field.TypeInt)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(dontstarvemod.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(dontstarvemod.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dontstarvemod.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dontstarvemod.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(dontstarvemod.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(dontstarvemod.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dontstarvemod.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(dontstarvemod.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Downloaded(); ok {
		_spec.SetField(dontstarvemod.FieldDownloaded, field.TypeBool, value)
	}
	if _u.mutation.DownloadedCleared() {
		_spec.ClearField(dontstarvemod.FieldDownloaded, field.TypeBool)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(dontstarvemod.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dontstarvemod.FieldConfig, value)
		})
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(dontstarvemod.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.RawConfig(); ok {
		_spec.SetField(dontstarvemod.FieldRawConfig, field.TypeString, value)
	}
	if _u.mutation.RawConfigCleared() {
		_spec.ClearField(dontstarvemod.FieldRawConfig, field.TypeString)
	}
	if _u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivesIDs(); len(nodes) > 0 && !_u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarvemod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DontStarveModUpdateOne is the builder for updating a single DontStarveMod entity.
type DontStarveModUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DontStarveModMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *DontStarveModUpdateOne) SetCreatedAt(v time.Time) *DontStarveModUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableCreatedAt(v *time.Time) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DontStarveModUpdateOne) SetUpdatedAt(v time.Time) *DontStarveModUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkshopID sets the "workshop_id" field.
func (_u *DontStarveModUpdateOne) SetWorkshopID(v string) *DontStarveModUpdateOne {
	_u.mutation.SetWorkshopID(v)
	return _u
}

// SetNillableWorkshopID sets the "workshop_id" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableWorkshopID(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetWorkshopID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DontStarveModUpdateOne) SetName(v string) *DontStarveModUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableName(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DontStarveModUpdateOne) ClearName() *DontStarveModUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetTimeCreated sets the "time_created" field.
func (_u *DontStarveModUpdateOne) SetTimeCreated(v int) *DontStarveModUpdateOne {
	_u.mutation.ResetTimeCreated()
	_u.mutation.SetTimeCreated(v)
	return _u
}

// SetNillableTimeCreated sets the "time_created" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableTimeCreated(v *int) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetTimeCreated(*v)
	}
	return _u
}

// AddTimeCreated adds value to the "time_created" field.
func (_u *DontStarveModUpdateOne) AddTimeCreated(v int) *DontStarveModUpdateOne {
	_u.mutation.AddTimeCreated(v)
	return _u
}

// ClearTimeCreated clears the value of the "time_created" field.
func (_u *DontStarveModUpdateOne) ClearTimeCreated() *DontStarveModUpdateOne {
	_u.mutation.ClearTimeCreated()
	return _u
}

// SetTimeUpdated sets the "time_updated" field.
func (_u *DontStarveModUpdateOne) SetTimeUpdated(v int) *DontStarveModUpdateOne {
	_u.mutation.ResetTimeUpdated()
	_u.mutation.SetTimeUpdated(v)
	return _u
}

// SetNillableTimeUpdated sets the "time_updated" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableTimeUpdated(v *int) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetTimeUpdated(*v)
	}
	return _u
}

// AddTimeUpdated adds value to the "time_updated" field.
func (_u *DontStarveModUpdateOne) AddTimeUpdated(v int) *DontStarveModUpdateOne {
	_u.mutation.AddTimeUpdated(v)
	return _u
}

// ClearTimeUpdated clears the value of the "time_updated" field.
func (_u *DontStarveModUpdateOne) ClearTimeUpdated() *DontStarveModUpdateOne {
	_u.mutation.ClearTimeUpdated()
	return _u
}

// SetImage sets the "image" field.
func (_u *DontStarveModUpdateOne) SetImage(v string) *DontStarveModUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableImage(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DontStarveModUpdateOne) ClearImage() *DontStarveModUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DontStarveModUpdateOne) SetDescription(v string) *DontStarveModUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableDescription(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DontStarveModUpdateOne) ClearDescription() *DontStarveModUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *DontStarveModUpdateOne) SetAuthor(v string) *DontStarveModUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableAuthor(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *DontStarveModUpdateOne) ClearAuthor() *DontStarveModUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetVersion sets the "version" field.
func (_u *DontStarveModUpdateOne) SetVersion(v string) *DontStarveModUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableVersion(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DontStarveModUpdateOne) ClearVersion() *DontStarveModUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetDownloaded sets the "downloaded" field.
func (_u *DontStarveModUpdateOne) SetDownloaded(v bool) *DontStarveModUpdateOne {
	_u.mutation.SetDownloaded(v)
	return _u
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableDownloaded(v *bool) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetDownloaded(*v)
	}
	return _u
}

// ClearDownloaded clears the value of the "downloaded" field.
func (_u *DontStarveModUpdateOne) ClearDownloaded() *DontStarveModUpdateOne {
	_u.mutation.ClearDownloaded()
	return _u
}

// SetConfig sets the "config" field.
func (_u *DontStarveModUpdateOne) SetConfig(v []dstety.DontStarveModConfig) *DontStarveModUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *DontStarveModUpdateOne) AppendConfig(v []dstety.DontStarveModConfig) *DontStarveModUpdateOne {
	_u.mutation.AppendConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DontStarveModUpdateOne) ClearConfig() *DontStarveModUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetRawConfig sets the "raw_config" field.
func (_u *DontStarveModUpdateOne) SetRawConfig(v string) *DontStarveModUpdateOne {
	_u.mutation.SetRawConfig(v)
	return _u
}

// SetNillableRawConfig sets the "raw_config" field if the given value is not nil.
func (_u *DontStarveModUpdateOne) SetNillableRawConfig(v *string) *DontStarveModUpdateOne {
	if v != nil {
		_u.SetRawConfig(*v)
	}
	return _u
}

// ClearRawConfig clears the value of the "raw_config" field.
func (_u *DontStarveModUpdateOne) ClearRawConfig() *DontStarveModUpdateOne {
	_u.mutation.ClearRawConfig()
	return _u
}

// AddArchiveIDs adds the "archives" edge to the DontStarveArchive entity by IDs.
func (_u *DontStarveModUpdateOne) AddArchiveIDs(ids ...string) *DontStarveModUpdateOne {
	_u.mutation.AddArchiveIDs(ids...)
	return _u
}

// AddArchives adds the "archives" edges to the DontStarveArchive entity.
func (_u *DontStarveModUpdateOne) AddArchives(v ...*DontStarveArchive) *DontStarveModUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchiveIDs(ids...)
}

// Mutation returns the DontStarveModMutation object of the builder.
func (_u *DontStarveModUpdateOne) Mutation() *DontStarveModMutation {
	return _u.mutation
}

// ClearArchives clears all "archives" edges to the DontStarveArchive entity.
func (_u *DontStarveModUpdateOne) ClearArchives() *DontStarveModUpdateOne {
	_u.mutation.ClearArchives()
	return _u
}

// RemoveArchiveIDs removes the "archives" edge to DontStarveArchive entities by IDs.
func (_u *DontStarveModUpdateOne) RemoveArchiveIDs(ids ...string) *DontStarveModUpdateOne {
	_u.mutation.RemoveArchiveIDs(ids...)
	return _u
}

// RemoveArchives removes "archives" edges to DontStarveArchive entities.
func (_u *DontStarveModUpdateOne) RemoveArchives(v ...*DontStarveArchive) *DontStarveModUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchiveIDs(ids...)
}

// Where appends a list predicates to the DontStarveModUpdate builder.
func (_u *DontStarveModUpdateOne) Where(ps ...predicate.DontStarveMod) *DontStarveModUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DontStarveModUpdateOne) Select(field string, fields ...string) *DontStarveModUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DontStarveMod entity.
func (_u *DontStarveModUpdateOne) Save(ctx context.Context) (*DontStarveMod, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DontStarveModUpdateOne) SaveX(ctx context.Context) *DontStarveMod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DontStarveModUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DontStarveModUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DontStarveModUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dontstarvemod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DontStarveModUpdateOne) sqlSave(ctx context.Context) (_node *DontStarveMod, err error) {
	_spec := sqlgraph.NewUpdateSpec(dontstarvemod.Table, dontstarvemod.Columns, sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DontStarveMod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dontstarvemod.FieldID)
		for _, f := range fields {
			if !dontstarvemod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dontstarvemod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvemod.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkshopID(); ok {
		_spec.SetField(dontstarvemod.FieldWorkshopID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dontstarvemod.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dontstarvemod.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.TimeCreated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeCreated(); ok {
		_spec.AddField(dontstarvemod.FieldTimeCreated, field.TypeInt, value)
	}
	if _u.mutation.TimeCreatedCleared() {
		_spec.ClearField(dontstarvemod.FieldTimeCreated, field.TypeInt)
	}
	if value, ok := _u.mutation.TimeUpdated(); ok {
		_spec.SetField(dontstarvemod.FieldTimeUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeUpdated(); ok {
		_spec.AddField(dontstarvemod.FieldTimeUpdated, field.TypeInt, value)
	}
	if _u.mutation.TimeUpdatedCleared() {
		_spec.ClearField(dontstarvemod.FieldTimeUpdated, field.TypeInt)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(dontstarvemod.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(dontstarvemod.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dontstarvemod.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dontstarvemod.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(dontstarvemod.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(dontstarvemod.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dontstarvemod.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(dontstarvemod.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Downloaded(); ok {
		_spec.SetField(dontstarvemod.FieldDownloaded, field.TypeBool, value)
	}
	if _u.mutation.DownloadedCleared() {
		_spec.ClearField(dontstarvemod.FieldDownloaded, field.TypeBool)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(dontstarvemod.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dontstarvemod.FieldConfig, value)
		})
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(dontstarvemod.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.RawConfig(); ok {
		_spec.SetField(dontstarvemod.FieldRawConfig, field.TypeString, value)
	}
	if _u.mutation.RawConfigCleared() {
		_spec.ClearField(dontstarvemod.FieldRawConfig, field.TypeString)
	}
	if _u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivesIDs(); len(nodes) > 0 && !_u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dontstarvemod.ArchivesTable,
			Columns: dontstarvemod.ArchivesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DontStarveMod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dontstarvemod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
