// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/internal/entity/dstety"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveArchiveCreate is the builder for creating a DontStarveArchive entity.
type DontStarveArchiveCreate struct {
	config
	mutation *DontStarveArchiveMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DontStarveArchiveCreate) SetCreatedAt(v time.Time) *DontStarveArchiveCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableCreatedAt(v *time.Time) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DontStarveArchiveCreate) SetUpdatedAt(v time.Time) *DontStarveArchiveCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableUpdatedAt(v *time.Time) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *DontStarveArchiveCreate) SetRemark(v string) *DontStarveArchiveCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableRemark(v *string) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetClusterName sets the "cluster_name" field.
func (_c *DontStarveArchiveCreate) SetClusterName(v string) *DontStarveArchiveCreate {
	_c.mutation.SetClusterName(v)
	return _c
}

// SetNillableClusterName sets the "cluster_name" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableClusterName(v *string) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetClusterName(*v)
	}
	return _c
}

// SetClusterPassword sets the "cluster_password" field.
func (_c *DontStarveArchiveCreate) SetClusterPassword(v string) *DontStarveArchiveCreate {
	_c.mutation.SetClusterPassword(v)
	return _c
}

// SetNillableClusterPassword sets the "cluster_password" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableClusterPassword(v *string) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetClusterPassword(*v)
	}
	return _c
}

// SetClusterDescription sets the "cluster_description" field.
func (_c *DontStarveArchiveCreate) SetClusterDescription(v string) *DontStarveArchiveCreate {
	_c.mutation.SetClusterDescription(v)
	return _c
}

// SetNillableClusterDescription sets the "cluster_description" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableClusterDescription(v *string) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetClusterDescription(*v)
	}
	return _c
}

// SetMaxPlayers sets the "max_players" field.
func (_c *DontStarveArchiveCreate) SetMaxPlayers(v int) *DontStarveArchiveCreate {
	_c.mutation.SetMaxPlayers(v)
	return _c
}

// SetNillableMaxPlayers sets the "max_players" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableMaxPlayers(v *int) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetMaxPlayers(*v)
	}
	return _c
}

// SetPvp sets the "pvp" field.
func (_c *DontStarveArchiveCreate) SetPvp(v bool) *DontStarveArchiveCreate {
	_c.mutation.SetPvp(v)
	return _c
}

// SetNillablePvp sets the "pvp" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillablePvp(v *bool) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetPvp(*v)
	}
	return _c
}

// SetWorld sets the "world" field.
func (_c *DontStarveArchiveCreate) SetWorld(v []dstety.DontStarveWorld) *DontStarveArchiveCreate {
	_c.mutation.SetWorld(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DontStarveArchiveCreate) SetID(v string) *DontStarveArchiveCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DontStarveArchiveCreate) SetNillableID(v *string) *DontStarveArchiveCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddModIDs adds the "mods" edge to the DontStarveMod entity by IDs.
func (_c *DontStarveArchiveCreate) AddModIDs(ids ...string) *DontStarveArchiveCreate {
	_c.mutation.AddModIDs(ids...)
	return _c
}

// AddMods adds the "mods" edges to the DontStarveMod entity.
func (_c *DontStarveArchiveCreate) AddMods(v ...*DontStarveMod) *DontStarveArchiveCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModIDs(ids...)
}

// Mutation returns the DontStarveArchiveMutation object of the builder.
func (_c *DontStarveArchiveCreate) Mutation() *DontStarveArchiveMutation {
	return _c.mutation
}

// Save creates the DontStarveArchive in the database.
func (_c *DontStarveArchiveCreate) Save(ctx context.Context) (*DontStarveArchive, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DontStarveArchiveCreate) SaveX(ctx context.Context) *DontStarveArchive {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveArchiveCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveArchiveCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DontStarveArchiveCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dontstarvearchive.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dontstarvearchive.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dontstarvearchive.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DontStarveArchiveCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DontStarveArchive.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DontStarveArchive.updated_at"`)}
	}
	return nil
}

func (_c *DontStarveArchiveCreate) sqlSave(ctx context.Context) (*DontStarveArchive, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DontStarveArchive.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DontStarveArchiveCreate) createSpec() (*DontStarveArchive, *sqlgraph.CreateSpec) {
	var (
		_node = &DontStarveArchive{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dontstarvearchive.Table, sqlgraph.NewFieldSpec(dontstarvearchive.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dontstarvearchive.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(dontstarvearchive.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.ClusterName(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterName, field.TypeString, value)
		_node.ClusterName = value
	}
	if value, ok := _c.mutation.ClusterPassword(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterPassword, field.TypeString, value)
		_node.ClusterPassword = value
	}
	if value, ok := _c.mutation.ClusterDescription(); ok {
		_spec.SetField(dontstarvearchive.FieldClusterDescription, field.TypeString, value)
		_node.ClusterDescription = value
	}
	if value, ok := _c.mutation.MaxPlayers(); ok {
		_spec.SetField(dontstarvearchive.FieldMaxPlayers, field.TypeInt, value)
		_node.MaxPlayers = value
	}
	if value, ok := _c.mutation.Pvp(); ok {
		_spec.SetField(dontstarvearchive.FieldPvp, field.TypeBool, value)
		_node.Pvp = value
	}
	if value, ok := _c.mutation.World(); ok {
		_spec.SetField(dontstarvearchive.FieldWorld, field.TypeJSON, value)
		_node.World = value
	}
	if nodes := _c.mutation.ModsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dontstarvearchive.ModsTable,
			Columns: dontstarvearchive.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DontStarveArchiveCreateBulk is the builder for creating many DontStarveArchive entities in bulk.
type DontStarveArchiveCreateBulk struct {
	config
	err      error
	builders []*DontStarveArchiveCreate
}

// Save creates the DontStarveArchive entities in the database.
func (_c *DontStarveArchiveCreateBulk) Save(ctx context.Context) ([]*DontStarveArchive, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DontStarveArchive, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DontStarveArchiveMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DontStarveArchiveCreateBulk) SaveX(ctx context.Context) []*DontStarveArchive {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DontStarveArchiveCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DontStarveArchiveCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
