// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DontStarveModQuery is the builder for querying DontStarveMod entities.
type DontStarveModQuery struct {
	config
	ctx          *QueryContext
	order        []dontstarvemod.OrderOption
	inters       []Interceptor
	predicates   []predicate.DontStarveMod
	withArchives *DontStarveArchiveQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DontStarveModQuery builder.
func (_q *DontStarveModQuery) Where(ps ...predicate.DontStarveMod) *DontStarveModQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DontStarveModQuery) Limit(limit int) *DontStarveModQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DontStarveModQuery) Offset(offset int) *DontStarveModQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DontStarveModQuery) Unique(unique bool) *DontStarveModQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DontStarveModQuery) Order(o ...dontstarvemod.OrderOption) *DontStarveModQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryArchives chains the current query on the "archives" edge.
func (_q *DontStarveModQuery) QueryArchives() *DontStarveArchiveQuery {
	query := (&DontStarveArchiveClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dontstarvemod.Table, dontstarvemod.FieldID, selector),
			sqlgraph.To(dontstarvearchive.Table, dontstarvearchive.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, dontstarvemod.ArchivesTable, dontstarvemod.ArchivesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DontStarveMod entity from the query.
// Returns a *NotFoundError when no DontStarveMod was found.
func (_q *DontStarveModQuery) First(ctx context.Context) (*DontStarveMod, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dontstarvemod.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DontStarveModQuery) FirstX(ctx context.Context) *DontStarveMod {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DontStarveMod ID from the query.
// Returns a *NotFoundError when no DontStarveMod ID was found.
func (_q *DontStarveModQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dontstarvemod.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DontStarveModQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DontStarveMod entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DontStarveMod entity is found.
// Returns a *NotFoundError when no DontStarveMod entities are found.
func (_q *DontStarveModQuery) Only(ctx context.Context) (*DontStarveMod, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dontstarvemod.Label}
	default:
		return nil, &NotSingularError{dontstarvemod.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DontStarveModQuery) OnlyX(ctx context.Context) *DontStarveMod {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DontStarveMod ID in the query.
// Returns a *NotSingularError when more than one DontStarveMod ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DontStarveModQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dontstarvemod.Label}
	default:
		err = &NotSingularError{dontstarvemod.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DontStarveModQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DontStarveMods.
func (_q *DontStarveModQuery) All(ctx context.Context) ([]*DontStarveMod, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DontStarveMod, *DontStarveModQuery]()
	return withInterceptors[[]*DontStarveMod](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DontStarveModQuery) AllX(ctx context.Context) []*DontStarveMod {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DontStarveMod IDs.
func (_q *DontStarveModQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dontstarvemod.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DontStarveModQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DontStarveModQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DontStarveModQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DontStarveModQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DontStarveModQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DontStarveModQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DontStarveModQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DontStarveModQuery) Clone() *DontStarveModQuery {
	if _q == nil {
		return nil
	}
	return &DontStarveModQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]dontstarvemod.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.DontStarveMod{}, _q.predicates...),
		withArchives: _q.withArchives.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithArchives tells the query-builder to eager-load the nodes that are connected to
// the "archives" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DontStarveModQuery) WithArchives(opts ...func(*DontStarveArchiveQuery)) *DontStarveModQuery {
	query := (&DontStarveArchiveClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withArchives = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DontStarveMod.Query().
//		GroupBy(dontstarvemod.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DontStarveModQuery) GroupBy(field string, fields ...string) *DontStarveModGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DontStarveModGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dontstarvemod.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DontStarveMod.Query().
//		Select(dontstarvemod.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DontStarveModQuery) Select(fields ...string) *DontStarveModSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DontStarveModSelect{DontStarveModQuery: _q}
	sbuild.label = dontstarvemod.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DontStarveModSelect configured with the given aggregations.
func (_q *DontStarveModQuery) Aggregate(fns ...AggregateFunc) *DontStarveModSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DontStarveModQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dontstarvemod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DontStarveModQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DontStarveMod, error) {
	var (
		nodes       = []*DontStarveMod{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withArchives != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DontStarveMod).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DontStarveMod{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withArchives; query != nil {
		if err := _q.loadArchives(ctx, query, nodes,
			func(n *DontStarveMod) { n.Edges.Archives = []*DontStarveArchive{} },
			func(n *DontStarveMod, e *DontStarveArchive) { n.Edges.Archives = append(n.Edges.Archives, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DontStarveModQuery) loadArchives(ctx context.Context, query *DontStarveArchiveQuery, nodes []*DontStarveMod, init func(*DontStarveMod), assign func(*DontStarveMod, *DontStarveArchive)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*DontStarveMod)
	nids := make(map[string]map[*DontStarveMod]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dontstarvemod.ArchivesTable)
		s.Join(joinT).On(s.C(dontstarvearchive.FieldID), joinT.C(dontstarvemod.ArchivesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(dontstarvemod.ArchivesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dontstarvemod.ArchivesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*DontStarveMod]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*DontStarveArchive](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "archives" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *DontStarveModQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DontStarveModQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dontstarvemod.Table, dontstarvemod.Columns, sqlgraph.NewFieldSpec(dontstarvemod.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dontstarvemod.FieldID)
		for i := range fields {
			if fields[i] != dontstarvemod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DontStarveModQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dontstarvemod.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dontstarvemod.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DontStarveModGroupBy is the group-by builder for DontStarveMod entities.
type DontStarveModGroupBy struct {
	selector
	build *DontStarveModQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DontStarveModGroupBy) Aggregate(fns ...AggregateFunc) *DontStarveModGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DontStarveModGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DontStarveModQuery, *DontStarveModGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DontStarveModGroupBy) sqlScan(ctx context.Context, root *DontStarveModQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DontStarveModSelect is the builder for selecting fields of DontStarveMod entities.
type DontStarveModSelect struct {
	*DontStarveModQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DontStarveModSelect) Aggregate(fns ...AggregateFunc) *DontStarveModSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DontStarveModSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DontStarveModQuery, *DontStarveModSelect](ctx, _s.DontStarveModQuery, _s, _s.inters, v)
}

func (_s *DontStarveModSelect) sqlScan(ctx context.Context, root *DontStarveModQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
