// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/internal/entity/dstety"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DontStarveMod is the model entity for the DontStarveMod schema.
type DontStarveMod struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// WorkshopID holds the value of the "workshop_id" field.
	WorkshopID string `json:"workshop_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TimeCreated holds the value of the "time_created" field.
	TimeCreated int `json:"time_created,omitempty"`
	// TimeUpdated holds the value of the "time_updated" field.
	TimeUpdated int `json:"time_updated,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Author holds the value of the "author" field.
	Author string `json:"author,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Downloaded holds the value of the "downloaded" field.
	Downloaded bool `json:"downloaded,omitempty"`
	// Config holds the value of the "config" field.
	Config []dstety.DontStarveModConfig `json:"config,omitempty"`
	// RawConfig holds the value of the "raw_config" field.
	RawConfig string `json:"raw_config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DontStarveModQuery when eager-loading is set.
	Edges        DontStarveModEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DontStarveModEdges holds the relations/edges for other nodes in the graph.
type DontStarveModEdges struct {
	// Archives holds the value of the archives edge.
	Archives []*DontStarveArchive `json:"archives,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArchivesOrErr returns the Archives value or an error if the edge
// was not loaded in eager-loading.
func (e DontStarveModEdges) ArchivesOrErr() ([]*DontStarveArchive, error) {
	if e.loadedTypes[0] {
		return e.Archives, nil
	}
	return nil, &NotLoadedError{edge: "archives"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DontStarveMod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dontstarvemod.FieldConfig:
			values[i] = new([]byte)
		case dontstarvemod.FieldDownloaded:
			values[i] = new(sql.NullBool)
		case dontstarvemod.FieldTimeCreated, dontstarvemod.FieldTimeUpdated:
			values[i] = new(sql.NullInt64)
		case dontstarvemod.FieldID, dontstarvemod.FieldWorkshopID, dontstarvemod.FieldName, dontstarvemod.FieldImage, dontstarvemod.FieldDescription, dontstarvemod.FieldAuthor, dontstarvemod.FieldVersion, dontstarvemod.FieldRawConfig:
			values[i] = new(sql.NullString)
		case dontstarvemod.FieldCreatedAt, dontstarvemod.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DontStarveMod fields.
func (_m *DontStarveMod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dontstarvemod.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case dontstarvemod.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dontstarvemod.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dontstarvemod.FieldWorkshopID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workshop_id", values[i])
			} else if value.Valid {
				_m.WorkshopID = value.String
			}
		case dontstarvemod.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case dontstarvemod.FieldTimeCreated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field time_created", values[i])
			} else if value.Valid {
				_m.TimeCreated = int(value.Int64)
			}
		case dontstarvemod.FieldTimeUpdated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field time_updated", values[i])
			} else if value.Valid {
				_m.TimeUpdated = int(value.Int64)
			}
		case dontstarvemod.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case dontstarvemod.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case dontstarvemod.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = value.String
			}
		case dontstarvemod.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case dontstarvemod.FieldDownloaded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field downloaded", values[i])
			} else if value.Valid {
				_m.Downloaded = value.Bool
			}
		case dontstarvemod.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case dontstarvemod.FieldRawConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_config", values[i])
			} else if value.Valid {
				_m.RawConfig = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DontStarveMod.
// This includes values selected through modifiers, order, etc.
func (_m *DontStarveMod) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArchives queries the "archives" edge of the DontStarveMod entity.
func (_m *DontStarveMod) QueryArchives() *DontStarveArchiveQuery {
	return NewDontStarveModClient(_m.config).QueryArchives(_m)
}

// Update returns a builder for updating this DontStarveMod.
// Note that you need to call DontStarveMod.Unwrap() before calling this method if this DontStarveMod
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DontStarveMod) Update() *DontStarveModUpdateOne {
	return NewDontStarveModClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DontStarveMod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DontStarveMod) Unwrap() *DontStarveMod {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DontStarveMod is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DontStarveMod) String() string {
	var builder strings.Builder
	builder.WriteString("DontStarveMod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("workshop_id=")
	builder.WriteString(_m.WorkshopID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("time_created=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeCreated))
	builder.WriteString(", ")
	builder.WriteString("time_updated=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeUpdated))
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("author=")
	builder.WriteString(_m.Author)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("downloaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.Downloaded))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("raw_config=")
	builder.WriteString(_m.RawConfig)
	builder.WriteByte(')')
	return builder.String()
}

// DontStarveMods is a parsable slice of DontStarveMod.
type DontStarveMods []*DontStarveMod
