// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarveadmin"
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/ent/predicate"
	"aurora-admin/internal/entity/dstety"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDontStarveAdmin   = "DontStarveAdmin"
	TypeDontStarveArchive = "DontStarveArchive"
	TypeDontStarveMod     = "DontStarveMod"
)

// DontStarveAdminMutation represents an operation that mutates the DontStarveAdmin nodes in the graph.
type DontStarveAdminMutation struct {
	config
	op            Op
	typ           string
	id            *string
	created_at    *time.Time
	updated_at    *time.Time
	name          *string
	klei_id       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*DontStarveAdmin, error)
	predicates    []predicate.DontStarveAdmin
}

var _ ent.Mutation = (*DontStarveAdminMutation)(nil)

// dontstarveadminOption allows management of the mutation configuration using functional options.
type dontstarveadminOption func(*DontStarveAdminMutation)

// newDontStarveAdminMutation creates new mutation for the DontStarveAdmin entity.
func newDontStarveAdminMutation(c config, op Op, opts ...dontstarveadminOption) *DontStarveAdminMutation {
	m := &DontStarveAdminMutation{
		config:        c,
		op:            op,
		typ:           TypeDontStarveAdmin,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDontStarveAdminID sets the ID field of the mutation.
func withDontStarveAdminID(id string) dontstarveadminOption {
	return func(m *DontStarveAdminMutation) {
		var (
			err   error
			once  sync.Once
			value *DontStarveAdmin
		)
		m.oldValue = func(ctx context.Context) (*DontStarveAdmin, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DontStarveAdmin.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDontStarveAdmin sets the old DontStarveAdmin of the mutation.
func withDontStarveAdmin(node *DontStarveAdmin) dontstarveadminOption {
	return func(m *DontStarveAdminMutation) {
		m.oldValue = func(context.Context) (*DontStarveAdmin, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DontStarveAdminMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DontStarveAdminMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DontStarveAdmin entities.
func (m *DontStarveAdminMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DontStarveAdminMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DontStarveAdminMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DontStarveAdmin.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *DontStarveAdminMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DontStarveAdminMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DontStarveAdmin entity.
// If the DontStarveAdmin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveAdminMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DontStarveAdminMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DontStarveAdminMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DontStarveAdminMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DontStarveAdmin entity.
// If the DontStarveAdmin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveAdminMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DontStarveAdminMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetName sets the "name" field.
func (m *DontStarveAdminMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DontStarveAdminMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the DontStarveAdmin entity.
// If the DontStarveAdmin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveAdminMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *DontStarveAdminMutation) ClearName() {
	m.name = nil
	m.clearedFields[dontstarveadmin.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *DontStarveAdminMutation) NameCleared() bool {
	_, ok := m.clearedFields[dontstarveadmin.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *DontStarveAdminMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, dontstarveadmin.FieldName)
}

// SetKleiID sets the "klei_id" field.
func (m *DontStarveAdminMutation) SetKleiID(s string) {
	m.klei_id = &s
}

// KleiID returns the value of the "klei_id" field in the mutation.
func (m *DontStarveAdminMutation) KleiID() (r string, exists bool) {
	v := m.klei_id
	if v == nil {
		return
	}
	return *v, true
}

// OldKleiID returns the old "klei_id" field's value of the DontStarveAdmin entity.
// If the DontStarveAdmin object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveAdminMutation) OldKleiID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKleiID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKleiID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKleiID: %w", err)
	}
	return oldValue.KleiID, nil
}

// ResetKleiID resets all changes to the "klei_id" field.
func (m *DontStarveAdminMutation) ResetKleiID() {
	m.klei_id = nil
}

// Where appends a list predicates to the DontStarveAdminMutation builder.
func (m *DontStarveAdminMutation) Where(ps ...predicate.DontStarveAdmin) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DontStarveAdminMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DontStarveAdminMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DontStarveAdmin, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DontStarveAdminMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DontStarveAdminMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DontStarveAdmin).
func (m *DontStarveAdminMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DontStarveAdminMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, dontstarveadmin.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dontstarveadmin.FieldUpdatedAt)
	}
	if m.name != nil {
		fields = append(fields, dontstarveadmin.FieldName)
	}
	if m.klei_id != nil {
		fields = append(fields, dontstarveadmin.FieldKleiID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DontStarveAdminMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dontstarveadmin.FieldCreatedAt:
		return m.CreatedAt()
	case dontstarveadmin.FieldUpdatedAt:
		return m.UpdatedAt()
	case dontstarveadmin.FieldName:
		return m.Name()
	case dontstarveadmin.FieldKleiID:
		return m.KleiID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DontStarveAdminMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dontstarveadmin.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dontstarveadmin.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case dontstarveadmin.FieldName:
		return m.OldName(ctx)
	case dontstarveadmin.FieldKleiID:
		return m.OldKleiID(ctx)
	}
	return nil, fmt.Errorf("unknown DontStarveAdmin field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveAdminMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dontstarveadmin.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dontstarveadmin.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case dontstarveadmin.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case dontstarveadmin.FieldKleiID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKleiID(v)
		return nil
	}
	return fmt.Errorf("unknown DontStarveAdmin field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DontStarveAdminMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DontStarveAdminMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveAdminMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DontStarveAdmin numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DontStarveAdminMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dontstarveadmin.FieldName) {
		fields = append(fields, dontstarveadmin.FieldName)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DontStarveAdminMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DontStarveAdminMutation) ClearField(name string) error {
	switch name {
	case dontstarveadmin.FieldName:
		m.ClearName()
		return nil
	}
	return fmt.Errorf("unknown DontStarveAdmin nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DontStarveAdminMutation) ResetField(name string) error {
	switch name {
	case dontstarveadmin.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dontstarveadmin.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case dontstarveadmin.FieldName:
		m.ResetName()
		return nil
	case dontstarveadmin.FieldKleiID:
		m.ResetKleiID()
		return nil
	}
	return fmt.Errorf("unknown DontStarveAdmin field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DontStarveAdminMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DontStarveAdminMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DontStarveAdminMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DontStarveAdminMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DontStarveAdminMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DontStarveAdminMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DontStarveAdminMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DontStarveAdmin unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DontStarveAdminMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DontStarveAdmin edge %s", name)
}

// DontStarveArchiveMutation represents an operation that mutates the DontStarveArchive nodes in the graph.
type DontStarveArchiveMutation struct {
	config
	op                  Op
	typ                 string
	id                  *string
	created_at          *time.Time
	updated_at          *time.Time
	remark              *string
	cluster_name        *string
	cluster_password    *string
	cluster_description *string
	max_players         *int
	addmax_players      *int
	pvp                 *bool
	world               *[]dstety.DontStarveWorld
	appendworld         []dstety.DontStarveWorld
	clearedFields       map[string]struct{}
	mods                map[string]struct{}
	removedmods         map[string]struct{}
	clearedmods         bool
	done                bool
	oldValue            func(context.Context) (*DontStarveArchive, error)
	predicates          []predicate.DontStarveArchive
}

var _ ent.Mutation = (*DontStarveArchiveMutation)(nil)

// dontstarvearchiveOption allows management of the mutation configuration using functional options.
type dontstarvearchiveOption func(*DontStarveArchiveMutation)

// newDontStarveArchiveMutation creates new mutation for the DontStarveArchive entity.
func newDontStarveArchiveMutation(c config, op Op, opts ...dontstarvearchiveOption) *DontStarveArchiveMutation {
	m := &DontStarveArchiveMutation{
		config:        c,
		op:            op,
		typ:           TypeDontStarveArchive,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDontStarveArchiveID sets the ID field of the mutation.
func withDontStarveArchiveID(id string) dontstarvearchiveOption {
	return func(m *DontStarveArchiveMutation) {
		var (
			err   error
			once  sync.Once
			value *DontStarveArchive
		)
		m.oldValue = func(ctx context.Context) (*DontStarveArchive, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DontStarveArchive.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDontStarveArchive sets the old DontStarveArchive of the mutation.
func withDontStarveArchive(node *DontStarveArchive) dontstarvearchiveOption {
	return func(m *DontStarveArchiveMutation) {
		m.oldValue = func(context.Context) (*DontStarveArchive, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DontStarveArchiveMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DontStarveArchiveMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DontStarveArchive entities.
func (m *DontStarveArchiveMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DontStarveArchiveMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DontStarveArchiveMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DontStarveArchive.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *DontStarveArchiveMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DontStarveArchiveMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DontStarveArchiveMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DontStarveArchiveMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DontStarveArchiveMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DontStarveArchiveMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetRemark sets the "remark" field.
func (m *DontStarveArchiveMutation) SetRemark(s string) {
	m.remark = &s
}

// Remark returns the value of the "remark" field in the mutation.
func (m *DontStarveArchiveMutation) Remark() (r string, exists bool) {
	v := m.remark
	if v == nil {
		return
	}
	return *v, true
}

// OldRemark returns the old "remark" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldRemark(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRemark is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRemark requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRemark: %w", err)
	}
	return oldValue.Remark, nil
}

// ClearRemark clears the value of the "remark" field.
func (m *DontStarveArchiveMutation) ClearRemark() {
	m.remark = nil
	m.clearedFields[dontstarvearchive.FieldRemark] = struct{}{}
}

// RemarkCleared returns if the "remark" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) RemarkCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldRemark]
	return ok
}

// ResetRemark resets all changes to the "remark" field.
func (m *DontStarveArchiveMutation) ResetRemark() {
	m.remark = nil
	delete(m.clearedFields, dontstarvearchive.FieldRemark)
}

// SetClusterName sets the "cluster_name" field.
func (m *DontStarveArchiveMutation) SetClusterName(s string) {
	m.cluster_name = &s
}

// ClusterName returns the value of the "cluster_name" field in the mutation.
func (m *DontStarveArchiveMutation) ClusterName() (r string, exists bool) {
	v := m.cluster_name
	if v == nil {
		return
	}
	return *v, true
}

// OldClusterName returns the old "cluster_name" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldClusterName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClusterName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClusterName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClusterName: %w", err)
	}
	return oldValue.ClusterName, nil
}

// ClearClusterName clears the value of the "cluster_name" field.
func (m *DontStarveArchiveMutation) ClearClusterName() {
	m.cluster_name = nil
	m.clearedFields[dontstarvearchive.FieldClusterName] = struct{}{}
}

// ClusterNameCleared returns if the "cluster_name" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) ClusterNameCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldClusterName]
	return ok
}

// ResetClusterName resets all changes to the "cluster_name" field.
func (m *DontStarveArchiveMutation) ResetClusterName() {
	m.cluster_name = nil
	delete(m.clearedFields, dontstarvearchive.FieldClusterName)
}

// SetClusterPassword sets the "cluster_password" field.
func (m *DontStarveArchiveMutation) SetClusterPassword(s string) {
	m.cluster_password = &s
}

// ClusterPassword returns the value of the "cluster_password" field in the mutation.
func (m *DontStarveArchiveMutation) ClusterPassword() (r string, exists bool) {
	v := m.cluster_password
	if v == nil {
		return
	}
	return *v, true
}

// OldClusterPassword returns the old "cluster_password" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldClusterPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClusterPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClusterPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClusterPassword: %w", err)
	}
	return oldValue.ClusterPassword, nil
}

// ClearClusterPassword clears the value of the "cluster_password" field.
func (m *DontStarveArchiveMutation) ClearClusterPassword() {
	m.cluster_password = nil
	m.clearedFields[dontstarvearchive.FieldClusterPassword] = struct{}{}
}

// ClusterPasswordCleared returns if the "cluster_password" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) ClusterPasswordCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldClusterPassword]
	return ok
}

// ResetClusterPassword resets all changes to the "cluster_password" field.
func (m *DontStarveArchiveMutation) ResetClusterPassword() {
	m.cluster_password = nil
	delete(m.clearedFields, dontstarvearchive.FieldClusterPassword)
}

// SetClusterDescription sets the "cluster_description" field.
func (m *DontStarveArchiveMutation) SetClusterDescription(s string) {
	m.cluster_description = &s
}

// ClusterDescription returns the value of the "cluster_description" field in the mutation.
func (m *DontStarveArchiveMutation) ClusterDescription() (r string, exists bool) {
	v := m.cluster_description
	if v == nil {
		return
	}
	return *v, true
}

// OldClusterDescription returns the old "cluster_description" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldClusterDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClusterDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClusterDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClusterDescription: %w", err)
	}
	return oldValue.ClusterDescription, nil
}

// ClearClusterDescription clears the value of the "cluster_description" field.
func (m *DontStarveArchiveMutation) ClearClusterDescription() {
	m.cluster_description = nil
	m.clearedFields[dontstarvearchive.FieldClusterDescription] = struct{}{}
}

// ClusterDescriptionCleared returns if the "cluster_description" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) ClusterDescriptionCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldClusterDescription]
	return ok
}

// ResetClusterDescription resets all changes to the "cluster_description" field.
func (m *DontStarveArchiveMutation) ResetClusterDescription() {
	m.cluster_description = nil
	delete(m.clearedFields, dontstarvearchive.FieldClusterDescription)
}

// SetMaxPlayers sets the "max_players" field.
func (m *DontStarveArchiveMutation) SetMaxPlayers(i int) {
	m.max_players = &i
	m.addmax_players = nil
}

// MaxPlayers returns the value of the "max_players" field in the mutation.
func (m *DontStarveArchiveMutation) MaxPlayers() (r int, exists bool) {
	v := m.max_players
	if v == nil {
		return
	}
	return *v, true
}

// OldMaxPlayers returns the old "max_players" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldMaxPlayers(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMaxPlayers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMaxPlayers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMaxPlayers: %w", err)
	}
	return oldValue.MaxPlayers, nil
}

// AddMaxPlayers adds i to the "max_players" field.
func (m *DontStarveArchiveMutation) AddMaxPlayers(i int) {
	if m.addmax_players != nil {
		*m.addmax_players += i
	} else {
		m.addmax_players = &i
	}
}

// AddedMaxPlayers returns the value that was added to the "max_players" field in this mutation.
func (m *DontStarveArchiveMutation) AddedMaxPlayers() (r int, exists bool) {
	v := m.addmax_players
	if v == nil {
		return
	}
	return *v, true
}

// ClearMaxPlayers clears the value of the "max_players" field.
func (m *DontStarveArchiveMutation) ClearMaxPlayers() {
	m.max_players = nil
	m.addmax_players = nil
	m.clearedFields[dontstarvearchive.FieldMaxPlayers] = struct{}{}
}

// MaxPlayersCleared returns if the "max_players" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) MaxPlayersCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldMaxPlayers]
	return ok
}

// ResetMaxPlayers resets all changes to the "max_players" field.
func (m *DontStarveArchiveMutation) ResetMaxPlayers() {
	m.max_players = nil
	m.addmax_players = nil
	delete(m.clearedFields, dontstarvearchive.FieldMaxPlayers)
}

// SetPvp sets the "pvp" field.
func (m *DontStarveArchiveMutation) SetPvp(b bool) {
	m.pvp = &b
}

// Pvp returns the value of the "pvp" field in the mutation.
func (m *DontStarveArchiveMutation) Pvp() (r bool, exists bool) {
	v := m.pvp
	if v == nil {
		return
	}
	return *v, true
}

// OldPvp returns the old "pvp" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldPvp(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPvp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPvp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPvp: %w", err)
	}
	return oldValue.Pvp, nil
}

// ClearPvp clears the value of the "pvp" field.
func (m *DontStarveArchiveMutation) ClearPvp() {
	m.pvp = nil
	m.clearedFields[dontstarvearchive.FieldPvp] = struct{}{}
}

// PvpCleared returns if the "pvp" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) PvpCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldPvp]
	return ok
}

// ResetPvp resets all changes to the "pvp" field.
func (m *DontStarveArchiveMutation) ResetPvp() {
	m.pvp = nil
	delete(m.clearedFields, dontstarvearchive.FieldPvp)
}

// SetWorld sets the "world" field.
func (m *DontStarveArchiveMutation) SetWorld(dsw []dstety.DontStarveWorld) {
	m.world = &dsw
	m.appendworld = nil
}

// World returns the value of the "world" field in the mutation.
func (m *DontStarveArchiveMutation) World() (r []dstety.DontStarveWorld, exists bool) {
	v := m.world
	if v == nil {
		return
	}
	return *v, true
}

// OldWorld returns the old "world" field's value of the DontStarveArchive entity.
// If the DontStarveArchive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveArchiveMutation) OldWorld(ctx context.Context) (v []dstety.DontStarveWorld, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorld is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorld requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorld: %w", err)
	}
	return oldValue.World, nil
}

// AppendWorld adds dsw to the "world" field.
func (m *DontStarveArchiveMutation) AppendWorld(dsw []dstety.DontStarveWorld) {
	m.appendworld = append(m.appendworld, dsw...)
}

// AppendedWorld returns the list of values that were appended to the "world" field in this mutation.
func (m *DontStarveArchiveMutation) AppendedWorld() ([]dstety.DontStarveWorld, bool) {
	if len(m.appendworld) == 0 {
		return nil, false
	}
	return m.appendworld, true
}

// ClearWorld clears the value of the "world" field.
func (m *DontStarveArchiveMutation) ClearWorld() {
	m.world = nil
	m.appendworld = nil
	m.clearedFields[dontstarvearchive.FieldWorld] = struct{}{}
}

// WorldCleared returns if the "world" field was cleared in this mutation.
func (m *DontStarveArchiveMutation) WorldCleared() bool {
	_, ok := m.clearedFields[dontstarvearchive.FieldWorld]
	return ok
}

// ResetWorld resets all changes to the "world" field.
func (m *DontStarveArchiveMutation) ResetWorld() {
	m.world = nil
	m.appendworld = nil
	delete(m.clearedFields, dontstarvearchive.FieldWorld)
}

// AddModIDs adds the "mods" edge to the DontStarveMod entity by ids.
func (m *DontStarveArchiveMutation) AddModIDs(ids ...string) {
	if m.mods == nil {
		m.mods = make(map[string]struct{})
	}
	for i := range ids {
		m.mods[ids[i]] = struct{}{}
	}
}

// ClearMods clears the "mods" edge to the DontStarveMod entity.
func (m *DontStarveArchiveMutation) ClearMods() {
	m.clearedmods = true
}

// ModsCleared reports if the "mods" edge to the DontStarveMod entity was cleared.
func (m *DontStarveArchiveMutation) ModsCleared() bool {
	return m.clearedmods
}

// RemoveModIDs removes the "mods" edge to the DontStarveMod entity by IDs.
func (m *DontStarveArchiveMutation) RemoveModIDs(ids ...string) {
	if m.removedmods == nil {
		m.removedmods = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.mods, ids[i])
		m.removedmods[ids[i]] = struct{}{}
	}
}

// RemovedMods returns the removed IDs of the "mods" edge to the DontStarveMod entity.
func (m *DontStarveArchiveMutation) RemovedModsIDs() (ids []string) {
	for id := range m.removedmods {
		ids = append(ids, id)
	}
	return
}

// ModsIDs returns the "mods" edge IDs in the mutation.
func (m *DontStarveArchiveMutation) ModsIDs() (ids []string) {
	for id := range m.mods {
		ids = append(ids, id)
	}
	return
}

// ResetMods resets all changes to the "mods" edge.
func (m *DontStarveArchiveMutation) ResetMods() {
	m.mods = nil
	m.clearedmods = false
	m.removedmods = nil
}

// Where appends a list predicates to the DontStarveArchiveMutation builder.
func (m *DontStarveArchiveMutation) Where(ps ...predicate.DontStarveArchive) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DontStarveArchiveMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DontStarveArchiveMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DontStarveArchive, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DontStarveArchiveMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DontStarveArchiveMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DontStarveArchive).
func (m *DontStarveArchiveMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DontStarveArchiveMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.created_at != nil {
		fields = append(fields, dontstarvearchive.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dontstarvearchive.FieldUpdatedAt)
	}
	if m.remark != nil {
		fields = append(fields, dontstarvearchive.FieldRemark)
	}
	if m.cluster_name != nil {
		fields = append(fields, dontstarvearchive.FieldClusterName)
	}
	if m.cluster_password != nil {
		fields = append(fields, dontstarvearchive.FieldClusterPassword)
	}
	if m.cluster_description != nil {
		fields = append(fields, dontstarvearchive.FieldClusterDescription)
	}
	if m.max_players != nil {
		fields = append(fields, dontstarvearchive.FieldMaxPlayers)
	}
	if m.pvp != nil {
		fields = append(fields, dontstarvearchive.FieldPvp)
	}
	if m.world != nil {
		fields = append(fields, dontstarvearchive.FieldWorld)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DontStarveArchiveMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dontstarvearchive.FieldCreatedAt:
		return m.CreatedAt()
	case dontstarvearchive.FieldUpdatedAt:
		return m.UpdatedAt()
	case dontstarvearchive.FieldRemark:
		return m.Remark()
	case dontstarvearchive.FieldClusterName:
		return m.ClusterName()
	case dontstarvearchive.FieldClusterPassword:
		return m.ClusterPassword()
	case dontstarvearchive.FieldClusterDescription:
		return m.ClusterDescription()
	case dontstarvearchive.FieldMaxPlayers:
		return m.MaxPlayers()
	case dontstarvearchive.FieldPvp:
		return m.Pvp()
	case dontstarvearchive.FieldWorld:
		return m.World()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DontStarveArchiveMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dontstarvearchive.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dontstarvearchive.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case dontstarvearchive.FieldRemark:
		return m.OldRemark(ctx)
	case dontstarvearchive.FieldClusterName:
		return m.OldClusterName(ctx)
	case dontstarvearchive.FieldClusterPassword:
		return m.OldClusterPassword(ctx)
	case dontstarvearchive.FieldClusterDescription:
		return m.OldClusterDescription(ctx)
	case dontstarvearchive.FieldMaxPlayers:
		return m.OldMaxPlayers(ctx)
	case dontstarvearchive.FieldPvp:
		return m.OldPvp(ctx)
	case dontstarvearchive.FieldWorld:
		return m.OldWorld(ctx)
	}
	return nil, fmt.Errorf("unknown DontStarveArchive field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveArchiveMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dontstarvearchive.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dontstarvearchive.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case dontstarvearchive.FieldRemark:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRemark(v)
		return nil
	case dontstarvearchive.FieldClusterName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClusterName(v)
		return nil
	case dontstarvearchive.FieldClusterPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClusterPassword(v)
		return nil
	case dontstarvearchive.FieldClusterDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClusterDescription(v)
		return nil
	case dontstarvearchive.FieldMaxPlayers:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMaxPlayers(v)
		return nil
	case dontstarvearchive.FieldPvp:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPvp(v)
		return nil
	case dontstarvearchive.FieldWorld:
		v, ok := value.([]dstety.DontStarveWorld)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorld(v)
		return nil
	}
	return fmt.Errorf("unknown DontStarveArchive field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DontStarveArchiveMutation) AddedFields() []string {
	var fields []string
	if m.addmax_players != nil {
		fields = append(fields, dontstarvearchive.FieldMaxPlayers)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DontStarveArchiveMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dontstarvearchive.FieldMaxPlayers:
		return m.AddedMaxPlayers()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveArchiveMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dontstarvearchive.FieldMaxPlayers:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMaxPlayers(v)
		return nil
	}
	return fmt.Errorf("unknown DontStarveArchive numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DontStarveArchiveMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dontstarvearchive.FieldRemark) {
		fields = append(fields, dontstarvearchive.FieldRemark)
	}
	if m.FieldCleared(dontstarvearchive.FieldClusterName) {
		fields = append(fields, dontstarvearchive.FieldClusterName)
	}
	if m.FieldCleared(dontstarvearchive.FieldClusterPassword) {
		fields = append(fields, dontstarvearchive.FieldClusterPassword)
	}
	if m.FieldCleared(dontstarvearchive.FieldClusterDescription) {
		fields = append(fields, dontstarvearchive.FieldClusterDescription)
	}
	if m.FieldCleared(dontstarvearchive.FieldMaxPlayers) {
		fields = append(fields, dontstarvearchive.FieldMaxPlayers)
	}
	if m.FieldCleared(dontstarvearchive.FieldPvp) {
		fields = append(fields, dontstarvearchive.FieldPvp)
	}
	if m.FieldCleared(dontstarvearchive.FieldWorld) {
		fields = append(fields, dontstarvearchive.FieldWorld)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DontStarveArchiveMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DontStarveArchiveMutation) ClearField(name string) error {
	switch name {
	case dontstarvearchive.FieldRemark:
		m.ClearRemark()
		return nil
	case dontstarvearchive.FieldClusterName:
		m.ClearClusterName()
		return nil
	case dontstarvearchive.FieldClusterPassword:
		m.ClearClusterPassword()
		return nil
	case dontstarvearchive.FieldClusterDescription:
		m.ClearClusterDescription()
		return nil
	case dontstarvearchive.FieldMaxPlayers:
		m.ClearMaxPlayers()
		return nil
	case dontstarvearchive.FieldPvp:
		m.ClearPvp()
		return nil
	case dontstarvearchive.FieldWorld:
		m.ClearWorld()
		return nil
	}
	return fmt.Errorf("unknown DontStarveArchive nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DontStarveArchiveMutation) ResetField(name string) error {
	switch name {
	case dontstarvearchive.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dontstarvearchive.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case dontstarvearchive.FieldRemark:
		m.ResetRemark()
		return nil
	case dontstarvearchive.FieldClusterName:
		m.ResetClusterName()
		return nil
	case dontstarvearchive.FieldClusterPassword:
		m.ResetClusterPassword()
		return nil
	case dontstarvearchive.FieldClusterDescription:
		m.ResetClusterDescription()
		return nil
	case dontstarvearchive.FieldMaxPlayers:
		m.ResetMaxPlayers()
		return nil
	case dontstarvearchive.FieldPvp:
		m.ResetPvp()
		return nil
	case dontstarvearchive.FieldWorld:
		m.ResetWorld()
		return nil
	}
	return fmt.Errorf("unknown DontStarveArchive field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DontStarveArchiveMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.mods != nil {
		edges = append(edges, dontstarvearchive.EdgeMods)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DontStarveArchiveMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dontstarvearchive.EdgeMods:
		ids := make([]ent.Value, 0, len(m.mods))
		for id := range m.mods {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DontStarveArchiveMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedmods != nil {
		edges = append(edges, dontstarvearchive.EdgeMods)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DontStarveArchiveMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case dontstarvearchive.EdgeMods:
		ids := make([]ent.Value, 0, len(m.removedmods))
		for id := range m.removedmods {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DontStarveArchiveMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedmods {
		edges = append(edges, dontstarvearchive.EdgeMods)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DontStarveArchiveMutation) EdgeCleared(name string) bool {
	switch name {
	case dontstarvearchive.EdgeMods:
		return m.clearedmods
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DontStarveArchiveMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown DontStarveArchive unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DontStarveArchiveMutation) ResetEdge(name string) error {
	switch name {
	case dontstarvearchive.EdgeMods:
		m.ResetMods()
		return nil
	}
	return fmt.Errorf("unknown DontStarveArchive edge %s", name)
}

// DontStarveModMutation represents an operation that mutates the DontStarveMod nodes in the graph.
type DontStarveModMutation struct {
	config
	op              Op
	typ             string
	id              *string
	created_at      *time.Time
	updated_at      *time.Time
	workshop_id     *string
	name            *string
	time_created    *int
	addtime_created *int
	time_updated    *int
	addtime_updated *int
	image           *string
	description     *string
	author          *string
	version         *string
	downloaded      *bool
	_config         *[]dstety.DontStarveModConfig
	append_config   []dstety.DontStarveModConfig
	raw_config      *string
	clearedFields   map[string]struct{}
	archives        map[string]struct{}
	removedarchives map[string]struct{}
	clearedarchives bool
	done            bool
	oldValue        func(context.Context) (*DontStarveMod, error)
	predicates      []predicate.DontStarveMod
}

var _ ent.Mutation = (*DontStarveModMutation)(nil)

// dontstarvemodOption allows management of the mutation configuration using functional options.
type dontstarvemodOption func(*DontStarveModMutation)

// newDontStarveModMutation creates new mutation for the DontStarveMod entity.
func newDontStarveModMutation(c config, op Op, opts ...dontstarvemodOption) *DontStarveModMutation {
	m := &DontStarveModMutation{
		config:        c,
		op:            op,
		typ:           TypeDontStarveMod,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDontStarveModID sets the ID field of the mutation.
func withDontStarveModID(id string) dontstarvemodOption {
	return func(m *DontStarveModMutation) {
		var (
			err   error
			once  sync.Once
			value *DontStarveMod
		)
		m.oldValue = func(ctx context.Context) (*DontStarveMod, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DontStarveMod.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDontStarveMod sets the old DontStarveMod of the mutation.
func withDontStarveMod(node *DontStarveMod) dontstarvemodOption {
	return func(m *DontStarveModMutation) {
		m.oldValue = func(context.Context) (*DontStarveMod, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DontStarveModMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DontStarveModMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DontStarveMod entities.
func (m *DontStarveModMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DontStarveModMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DontStarveModMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DontStarveMod.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *DontStarveModMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DontStarveModMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DontStarveModMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DontStarveModMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DontStarveModMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DontStarveModMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetWorkshopID sets the "workshop_id" field.
func (m *DontStarveModMutation) SetWorkshopID(s string) {
	m.workshop_id = &s
}

// WorkshopID returns the value of the "workshop_id" field in the mutation.
func (m *DontStarveModMutation) WorkshopID() (r string, exists bool) {
	v := m.workshop_id
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkshopID returns the old "workshop_id" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldWorkshopID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkshopID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkshopID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkshopID: %w", err)
	}
	return oldValue.WorkshopID, nil
}

// ResetWorkshopID resets all changes to the "workshop_id" field.
func (m *DontStarveModMutation) ResetWorkshopID() {
	m.workshop_id = nil
}

// SetName sets the "name" field.
func (m *DontStarveModMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DontStarveModMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *DontStarveModMutation) ClearName() {
	m.name = nil
	m.clearedFields[dontstarvemod.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *DontStarveModMutation) NameCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *DontStarveModMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, dontstarvemod.FieldName)
}

// SetTimeCreated sets the "time_created" field.
func (m *DontStarveModMutation) SetTimeCreated(i int) {
	m.time_created = &i
	m.addtime_created = nil
}

// TimeCreated returns the value of the "time_created" field in the mutation.
func (m *DontStarveModMutation) TimeCreated() (r int, exists bool) {
	v := m.time_created
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeCreated returns the old "time_created" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldTimeCreated(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeCreated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeCreated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeCreated: %w", err)
	}
	return oldValue.TimeCreated, nil
}

// AddTimeCreated adds i to the "time_created" field.
func (m *DontStarveModMutation) AddTimeCreated(i int) {
	if m.addtime_created != nil {
		*m.addtime_created += i
	} else {
		m.addtime_created = &i
	}
}

// AddedTimeCreated returns the value that was added to the "time_created" field in this mutation.
func (m *DontStarveModMutation) AddedTimeCreated() (r int, exists bool) {
	v := m.addtime_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearTimeCreated clears the value of the "time_created" field.
func (m *DontStarveModMutation) ClearTimeCreated() {
	m.time_created = nil
	m.addtime_created = nil
	m.clearedFields[dontstarvemod.FieldTimeCreated] = struct{}{}
}

// TimeCreatedCleared returns if the "time_created" field was cleared in this mutation.
func (m *DontStarveModMutation) TimeCreatedCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldTimeCreated]
	return ok
}

// ResetTimeCreated resets all changes to the "time_created" field.
func (m *DontStarveModMutation) ResetTimeCreated() {
	m.time_created = nil
	m.addtime_created = nil
	delete(m.clearedFields, dontstarvemod.FieldTimeCreated)
}

// SetTimeUpdated sets the "time_updated" field.
func (m *DontStarveModMutation) SetTimeUpdated(i int) {
	m.time_updated = &i
	m.addtime_updated = nil
}

// TimeUpdated returns the value of the "time_updated" field in the mutation.
func (m *DontStarveModMutation) TimeUpdated() (r int, exists bool) {
	v := m.time_updated
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeUpdated returns the old "time_updated" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldTimeUpdated(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeUpdated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeUpdated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeUpdated: %w", err)
	}
	return oldValue.TimeUpdated, nil
}

// AddTimeUpdated adds i to the "time_updated" field.
func (m *DontStarveModMutation) AddTimeUpdated(i int) {
	if m.addtime_updated != nil {
		*m.addtime_updated += i
	} else {
		m.addtime_updated = &i
	}
}

// AddedTimeUpdated returns the value that was added to the "time_updated" field in this mutation.
func (m *DontStarveModMutation) AddedTimeUpdated() (r int, exists bool) {
	v := m.addtime_updated
	if v == nil {
		return
	}
	return *v, true
}

// ClearTimeUpdated clears the value of the "time_updated" field.
func (m *DontStarveModMutation) ClearTimeUpdated() {
	m.time_updated = nil
	m.addtime_updated = nil
	m.clearedFields[dontstarvemod.FieldTimeUpdated] = struct{}{}
}

// TimeUpdatedCleared returns if the "time_updated" field was cleared in this mutation.
func (m *DontStarveModMutation) TimeUpdatedCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldTimeUpdated]
	return ok
}

// ResetTimeUpdated resets all changes to the "time_updated" field.
func (m *DontStarveModMutation) ResetTimeUpdated() {
	m.time_updated = nil
	m.addtime_updated = nil
	delete(m.clearedFields, dontstarvemod.FieldTimeUpdated)
}

// SetImage sets the "image" field.
func (m *DontStarveModMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *DontStarveModMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ClearImage clears the value of the "image" field.
func (m *DontStarveModMutation) ClearImage() {
	m.image = nil
	m.clearedFields[dontstarvemod.FieldImage] = struct{}{}
}

// ImageCleared returns if the "image" field was cleared in this mutation.
func (m *DontStarveModMutation) ImageCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldImage]
	return ok
}

// ResetImage resets all changes to the "image" field.
func (m *DontStarveModMutation) ResetImage() {
	m.image = nil
	delete(m.clearedFields, dontstarvemod.FieldImage)
}

// SetDescription sets the "description" field.
func (m *DontStarveModMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *DontStarveModMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *DontStarveModMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[dontstarvemod.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *DontStarveModMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *DontStarveModMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, dontstarvemod.FieldDescription)
}

// SetAuthor sets the "author" field.
func (m *DontStarveModMutation) SetAuthor(s string) {
	m.author = &s
}

// Author returns the value of the "author" field in the mutation.
func (m *DontStarveModMutation) Author() (r string, exists bool) {
	v := m.author
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthor returns the old "author" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldAuthor(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthor: %w", err)
	}
	return oldValue.Author, nil
}

// ClearAuthor clears the value of the "author" field.
func (m *DontStarveModMutation) ClearAuthor() {
	m.author = nil
	m.clearedFields[dontstarvemod.FieldAuthor] = struct{}{}
}

// AuthorCleared returns if the "author" field was cleared in this mutation.
func (m *DontStarveModMutation) AuthorCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldAuthor]
	return ok
}

// ResetAuthor resets all changes to the "author" field.
func (m *DontStarveModMutation) ResetAuthor() {
	m.author = nil
	delete(m.clearedFields, dontstarvemod.FieldAuthor)
}

// SetVersion sets the "version" field.
func (m *DontStarveModMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *DontStarveModMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ClearVersion clears the value of the "version" field.
func (m *DontStarveModMutation) ClearVersion() {
	m.version = nil
	m.clearedFields[dontstarvemod.FieldVersion] = struct{}{}
}

// VersionCleared returns if the "version" field was cleared in this mutation.
func (m *DontStarveModMutation) VersionCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldVersion]
	return ok
}

// ResetVersion resets all changes to the "version" field.
func (m *DontStarveModMutation) ResetVersion() {
	m.version = nil
	delete(m.clearedFields, dontstarvemod.FieldVersion)
}

// SetDownloaded sets the "downloaded" field.
func (m *DontStarveModMutation) SetDownloaded(b bool) {
	m.downloaded = &b
}

// Downloaded returns the value of the "downloaded" field in the mutation.
func (m *DontStarveModMutation) Downloaded() (r bool, exists bool) {
	v := m.downloaded
	if v == nil {
		return
	}
	return *v, true
}

// OldDownloaded returns the old "downloaded" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldDownloaded(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDownloaded is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDownloaded requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDownloaded: %w", err)
	}
	return oldValue.Downloaded, nil
}

// ClearDownloaded clears the value of the "downloaded" field.
func (m *DontStarveModMutation) ClearDownloaded() {
	m.downloaded = nil
	m.clearedFields[dontstarvemod.FieldDownloaded] = struct{}{}
}

// DownloadedCleared returns if the "downloaded" field was cleared in this mutation.
func (m *DontStarveModMutation) DownloadedCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldDownloaded]
	return ok
}

// ResetDownloaded resets all changes to the "downloaded" field.
func (m *DontStarveModMutation) ResetDownloaded() {
	m.downloaded = nil
	delete(m.clearedFields, dontstarvemod.FieldDownloaded)
}

// SetConfig sets the "config" field.
func (m *DontStarveModMutation) SetConfig(dsmc []dstety.DontStarveModConfig) {
	m._config = &dsmc
	m.append_config = nil
}

// Config returns the value of the "config" field in the mutation.
func (m *DontStarveModMutation) Config() (r []dstety.DontStarveModConfig, exists bool) {
	v := m._config
	if v == nil {
		return
	}
	return *v, true
}

// OldConfig returns the old "config" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldConfig(ctx context.Context) (v []dstety.DontStarveModConfig, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConfig is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConfig requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConfig: %w", err)
	}
	return oldValue.Config, nil
}

// AppendConfig adds dsmc to the "config" field.
func (m *DontStarveModMutation) AppendConfig(dsmc []dstety.DontStarveModConfig) {
	m.append_config = append(m.append_config, dsmc...)
}

// AppendedConfig returns the list of values that were appended to the "config" field in this mutation.
func (m *DontStarveModMutation) AppendedConfig() ([]dstety.DontStarveModConfig, bool) {
	if len(m.append_config) == 0 {
		return nil, false
	}
	return m.append_config, true
}

// ClearConfig clears the value of the "config" field.
func (m *DontStarveModMutation) ClearConfig() {
	m._config = nil
	m.append_config = nil
	m.clearedFields[dontstarvemod.FieldConfig] = struct{}{}
}

// ConfigCleared returns if the "config" field was cleared in this mutation.
func (m *DontStarveModMutation) ConfigCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldConfig]
	return ok
}

// ResetConfig resets all changes to the "config" field.
func (m *DontStarveModMutation) ResetConfig() {
	m._config = nil
	m.append_config = nil
	delete(m.clearedFields, dontstarvemod.FieldConfig)
}

// SetRawConfig sets the "raw_config" field.
func (m *DontStarveModMutation) SetRawConfig(s string) {
	m.raw_config = &s
}

// RawConfig returns the value of the "raw_config" field in the mutation.
func (m *DontStarveModMutation) RawConfig() (r string, exists bool) {
	v := m.raw_config
	if v == nil {
		return
	}
	return *v, true
}

// OldRawConfig returns the old "raw_config" field's value of the DontStarveMod entity.
// If the DontStarveMod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DontStarveModMutation) OldRawConfig(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRawConfig is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRawConfig requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRawConfig: %w", err)
	}
	return oldValue.RawConfig, nil
}

// ClearRawConfig clears the value of the "raw_config" field.
func (m *DontStarveModMutation) ClearRawConfig() {
	m.raw_config = nil
	m.clearedFields[dontstarvemod.FieldRawConfig] = struct{}{}
}

// RawConfigCleared returns if the "raw_config" field was cleared in this mutation.
func (m *DontStarveModMutation) RawConfigCleared() bool {
	_, ok := m.clearedFields[dontstarvemod.FieldRawConfig]
	return ok
}

// ResetRawConfig resets all changes to the "raw_config" field.
func (m *DontStarveModMutation) ResetRawConfig() {
	m.raw_config = nil
	delete(m.clearedFields, dontstarvemod.FieldRawConfig)
}

// AddArchiveIDs adds the "archives" edge to the DontStarveArchive entity by ids.
func (m *DontStarveModMutation) AddArchiveIDs(ids ...string) {
	if m.archives == nil {
		m.archives = make(map[string]struct{})
	}
	for i := range ids {
		m.archives[ids[i]] = struct{}{}
	}
}

// ClearArchives clears the "archives" edge to the DontStarveArchive entity.
func (m *DontStarveModMutation) ClearArchives() {
	m.clearedarchives = true
}

// ArchivesCleared reports if the "archives" edge to the DontStarveArchive entity was cleared.
func (m *DontStarveModMutation) ArchivesCleared() bool {
	return m.clearedarchives
}

// RemoveArchiveIDs removes the "archives" edge to the DontStarveArchive entity by IDs.
func (m *DontStarveModMutation) RemoveArchiveIDs(ids ...string) {
	if m.removedarchives == nil {
		m.removedarchives = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.archives, ids[i])
		m.removedarchives[ids[i]] = struct{}{}
	}
}

// RemovedArchives returns the removed IDs of the "archives" edge to the DontStarveArchive entity.
func (m *DontStarveModMutation) RemovedArchivesIDs() (ids []string) {
	for id := range m.removedarchives {
		ids = append(ids, id)
	}
	return
}

// ArchivesIDs returns the "archives" edge IDs in the mutation.
func (m *DontStarveModMutation) ArchivesIDs() (ids []string) {
	for id := range m.archives {
		ids = append(ids, id)
	}
	return
}

// ResetArchives resets all changes to the "archives" edge.
func (m *DontStarveModMutation) ResetArchives() {
	m.archives = nil
	m.clearedarchives = false
	m.removedarchives = nil
}

// Where appends a list predicates to the DontStarveModMutation builder.
func (m *DontStarveModMutation) Where(ps ...predicate.DontStarveMod) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DontStarveModMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DontStarveModMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DontStarveMod, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DontStarveModMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DontStarveModMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DontStarveMod).
func (m *DontStarveModMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DontStarveModMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.created_at != nil {
		fields = append(fields, dontstarvemod.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dontstarvemod.FieldUpdatedAt)
	}
	if m.workshop_id != nil {
		fields = append(fields, dontstarvemod.FieldWorkshopID)
	}
	if m.name != nil {
		fields = append(fields, dontstarvemod.FieldName)
	}
	if m.time_created != nil {
		fields = append(fields, dontstarvemod.FieldTimeCreated)
	}
	if m.time_updated != nil {
		fields = append(fields, dontstarvemod.FieldTimeUpdated)
	}
	if m.image != nil {
		fields = append(fields, dontstarvemod.FieldImage)
	}
	if m.description != nil {
		fields = append(fields, dontstarvemod.FieldDescription)
	}
	if m.author != nil {
		fields = append(fields, dontstarvemod.FieldAuthor)
	}
	if m.version != nil {
		fields = append(fields, dontstarvemod.FieldVersion)
	}
	if m.downloaded != nil {
		fields = append(fields, dontstarvemod.FieldDownloaded)
	}
	if m._config != nil {
		fields = append(fields, dontstarvemod.FieldConfig)
	}
	if m.raw_config != nil {
		fields = append(fields, dontstarvemod.FieldRawConfig)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DontStarveModMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dontstarvemod.FieldCreatedAt:
		return m.CreatedAt()
	case dontstarvemod.FieldUpdatedAt:
		return m.UpdatedAt()
	case dontstarvemod.FieldWorkshopID:
		return m.WorkshopID()
	case dontstarvemod.FieldName:
		return m.Name()
	case dontstarvemod.FieldTimeCreated:
		return m.TimeCreated()
	case dontstarvemod.FieldTimeUpdated:
		return m.TimeUpdated()
	case dontstarvemod.FieldImage:
		return m.Image()
	case dontstarvemod.FieldDescription:
		return m.Description()
	case dontstarvemod.FieldAuthor:
		return m.Author()
	case dontstarvemod.FieldVersion:
		return m.Version()
	case dontstarvemod.FieldDownloaded:
		return m.Downloaded()
	case dontstarvemod.FieldConfig:
		return m.Config()
	case dontstarvemod.FieldRawConfig:
		return m.RawConfig()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DontStarveModMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dontstarvemod.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dontstarvemod.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case dontstarvemod.FieldWorkshopID:
		return m.OldWorkshopID(ctx)
	case dontstarvemod.FieldName:
		return m.OldName(ctx)
	case dontstarvemod.FieldTimeCreated:
		return m.OldTimeCreated(ctx)
	case dontstarvemod.FieldTimeUpdated:
		return m.OldTimeUpdated(ctx)
	case dontstarvemod.FieldImage:
		return m.OldImage(ctx)
	case dontstarvemod.FieldDescription:
		return m.OldDescription(ctx)
	case dontstarvemod.FieldAuthor:
		return m.OldAuthor(ctx)
	case dontstarvemod.FieldVersion:
		return m.OldVersion(ctx)
	case dontstarvemod.FieldDownloaded:
		return m.OldDownloaded(ctx)
	case dontstarvemod.FieldConfig:
		return m.OldConfig(ctx)
	case dontstarvemod.FieldRawConfig:
		return m.OldRawConfig(ctx)
	}
	return nil, fmt.Errorf("unknown DontStarveMod field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveModMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dontstarvemod.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dontstarvemod.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case dontstarvemod.FieldWorkshopID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkshopID(v)
		return nil
	case dontstarvemod.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case dontstarvemod.FieldTimeCreated:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeCreated(v)
		return nil
	case dontstarvemod.FieldTimeUpdated:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeUpdated(v)
		return nil
	case dontstarvemod.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case dontstarvemod.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case dontstarvemod.FieldAuthor:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthor(v)
		return nil
	case dontstarvemod.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case dontstarvemod.FieldDownloaded:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDownloaded(v)
		return nil
	case dontstarvemod.FieldConfig:
		v, ok := value.([]dstety.DontStarveModConfig)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConfig(v)
		return nil
	case dontstarvemod.FieldRawConfig:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRawConfig(v)
		return nil
	}
	return fmt.Errorf("unknown DontStarveMod field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DontStarveModMutation) AddedFields() []string {
	var fields []string
	if m.addtime_created != nil {
		fields = append(fields, dontstarvemod.FieldTimeCreated)
	}
	if m.addtime_updated != nil {
		fields = append(fields, dontstarvemod.FieldTimeUpdated)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DontStarveModMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dontstarvemod.FieldTimeCreated:
		return m.AddedTimeCreated()
	case dontstarvemod.FieldTimeUpdated:
		return m.AddedTimeUpdated()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DontStarveModMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dontstarvemod.FieldTimeCreated:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTimeCreated(v)
		return nil
	case dontstarvemod.FieldTimeUpdated:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTimeUpdated(v)
		return nil
	}
	return fmt.Errorf("unknown DontStarveMod numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DontStarveModMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dontstarvemod.FieldName) {
		fields = append(fields, dontstarvemod.FieldName)
	}
	if m.FieldCleared(dontstarvemod.FieldTimeCreated) {
		fields = append(fields, dontstarvemod.FieldTimeCreated)
	}
	if m.FieldCleared(dontstarvemod.FieldTimeUpdated) {
		fields = append(fields, dontstarvemod.FieldTimeUpdated)
	}
	if m.FieldCleared(dontstarvemod.FieldImage) {
		fields = append(fields, dontstarvemod.FieldImage)
	}
	if m.FieldCleared(dontstarvemod.FieldDescription) {
		fields = append(fields, dontstarvemod.FieldDescription)
	}
	if m.FieldCleared(dontstarvemod.FieldAuthor) {
		fields = append(fields, dontstarvemod.FieldAuthor)
	}
	if m.FieldCleared(dontstarvemod.FieldVersion) {
		fields = append(fields, dontstarvemod.FieldVersion)
	}
	if m.FieldCleared(dontstarvemod.FieldDownloaded) {
		fields = append(fields, dontstarvemod.FieldDownloaded)
	}
	if m.FieldCleared(dontstarvemod.FieldConfig) {
		fields = append(fields, dontstarvemod.FieldConfig)
	}
	if m.FieldCleared(dontstarvemod.FieldRawConfig) {
		fields = append(fields, dontstarvemod.FieldRawConfig)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DontStarveModMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DontStarveModMutation) ClearField(name string) error {
	switch name {
	case dontstarvemod.FieldName:
		m.ClearName()
		return nil
	case dontstarvemod.FieldTimeCreated:
		m.ClearTimeCreated()
		return nil
	case dontstarvemod.FieldTimeUpdated:
		m.ClearTimeUpdated()
		return nil
	case dontstarvemod.FieldImage:
		m.ClearImage()
		return nil
	case dontstarvemod.FieldDescription:
		m.ClearDescription()
		return nil
	case dontstarvemod.FieldAuthor:
		m.ClearAuthor()
		return nil
	case dontstarvemod.FieldVersion:
		m.ClearVersion()
		return nil
	case dontstarvemod.FieldDownloaded:
		m.ClearDownloaded()
		return nil
	case dontstarvemod.FieldConfig:
		m.ClearConfig()
		return nil
	case dontstarvemod.FieldRawConfig:
		m.ClearRawConfig()
		return nil
	}
	return fmt.Errorf("unknown DontStarveMod nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DontStarveModMutation) ResetField(name string) error {
	switch name {
	case dontstarvemod.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dontstarvemod.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case dontstarvemod.FieldWorkshopID:
		m.ResetWorkshopID()
		return nil
	case dontstarvemod.FieldName:
		m.ResetName()
		return nil
	case dontstarvemod.FieldTimeCreated:
		m.ResetTimeCreated()
		return nil
	case dontstarvemod.FieldTimeUpdated:
		m.ResetTimeUpdated()
		return nil
	case dontstarvemod.FieldImage:
		m.ResetImage()
		return nil
	case dontstarvemod.FieldDescription:
		m.ResetDescription()
		return nil
	case dontstarvemod.FieldAuthor:
		m.ResetAuthor()
		return nil
	case dontstarvemod.FieldVersion:
		m.ResetVersion()
		return nil
	case dontstarvemod.FieldDownloaded:
		m.ResetDownloaded()
		return nil
	case dontstarvemod.FieldConfig:
		m.ResetConfig()
		return nil
	case dontstarvemod.FieldRawConfig:
		m.ResetRawConfig()
		return nil
	}
	return fmt.Errorf("unknown DontStarveMod field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DontStarveModMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.archives != nil {
		edges = append(edges, dontstarvemod.EdgeArchives)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DontStarveModMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dontstarvemod.EdgeArchives:
		ids := make([]ent.Value, 0, len(m.archives))
		for id := range m.archives {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DontStarveModMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedarchives != nil {
		edges = append(edges, dontstarvemod.EdgeArchives)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DontStarveModMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case dontstarvemod.EdgeArchives:
		ids := make([]ent.Value, 0, len(m.removedarchives))
		for id := range m.removedarchives {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DontStarveModMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedarchives {
		edges = append(edges, dontstarvemod.EdgeArchives)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DontStarveModMutation) EdgeCleared(name string) bool {
	switch name {
	case dontstarvemod.EdgeArchives:
		return m.clearedarchives
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DontStarveModMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown DontStarveMod unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DontStarveModMutation) ResetEdge(name string) error {
	switch name {
	case dontstarvemod.EdgeArchives:
		m.ResetArchives()
		return nil
	}
	return fmt.Errorf("unknown DontStarveMod edge %s", name)
}
