// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aurora-admin/ent/dontstarveadmin"
	"aurora-admin/ent/dontstarvearchive"
	"aurora-admin/ent/dontstarvemod"
	"aurora-admin/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dontstarveadminFields := schema.DontStarveAdmin{}.Fields()
	_ = dontstarveadminFields
	// dontstarveadminDescCreatedAt is the schema descriptor for created_at field.
	dontstarveadminDescCreatedAt := dontstarveadminFields[1].Descriptor()
	// dontstarveadmin.DefaultCreatedAt holds the default value on creation for the created_at field.
	dontstarveadmin.DefaultCreatedAt = dontstarveadminDescCreatedAt.Default.(func() time.Time)
	// dontstarveadminDescUpdatedAt is the schema descriptor for updated_at field.
	dontstarveadminDescUpdatedAt := dontstarveadminFields[2].Descriptor()
	// dontstarveadmin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dontstarveadmin.DefaultUpdatedAt = dontstarveadminDescUpdatedAt.Default.(func() time.Time)
	// dontstarveadmin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dontstarveadmin.UpdateDefaultUpdatedAt = dontstarveadminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dontstarveadminDescID is the schema descriptor for id field.
	dontstarveadminDescID := dontstarveadminFields[0].Descriptor()
	// dontstarveadmin.DefaultID holds the default value on creation for the id field.
	dontstarveadmin.DefaultID = dontstarveadminDescID.Default.(func() string)
	dontstarvearchiveFields := schema.DontStarveArchive{}.Fields()
	_ = dontstarvearchiveFields
	// dontstarvearchiveDescCreatedAt is the schema descriptor for created_at field.
	dontstarvearchiveDescCreatedAt := dontstarvearchiveFields[1].Descriptor()
	// dontstarvearchive.DefaultCreatedAt holds the default value on creation for the created_at field.
	dontstarvearchive.DefaultCreatedAt = dontstarvearchiveDescCreatedAt.Default.(func() time.Time)
	// dontstarvearchiveDescUpdatedAt is the schema descriptor for updated_at field.
	dontstarvearchiveDescUpdatedAt := dontstarvearchiveFields[2].Descriptor()
	// dontstarvearchive.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dontstarvearchive.DefaultUpdatedAt = dontstarvearchiveDescUpdatedAt.Default.(func() time.Time)
	// dontstarvearchive.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dontstarvearchive.UpdateDefaultUpdatedAt = dontstarvearchiveDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dontstarvearchiveDescID is the schema descriptor for id field.
	dontstarvearchiveDescID := dontstarvearchiveFields[0].Descriptor()
	// dontstarvearchive.DefaultID holds the default value on creation for the id field.
	dontstarvearchive.DefaultID = dontstarvearchiveDescID.Default.(func() string)
	dontstarvemodFields := schema.DontStarveMod{}.Fields()
	_ = dontstarvemodFields
	// dontstarvemodDescCreatedAt is the schema descriptor for created_at field.
	dontstarvemodDescCreatedAt := dontstarvemodFields[1].Descriptor()
	// dontstarvemod.DefaultCreatedAt holds the default value on creation for the created_at field.
	dontstarvemod.DefaultCreatedAt = dontstarvemodDescCreatedAt.Default.(func() time.Time)
	// dontstarvemodDescUpdatedAt is the schema descriptor for updated_at field.
	dontstarvemodDescUpdatedAt := dontstarvemodFields[2].Descriptor()
	// dontstarvemod.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dontstarvemod.DefaultUpdatedAt = dontstarvemodDescUpdatedAt.Default.(func() time.Time)
	// dontstarvemod.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dontstarvemod.UpdateDefaultUpdatedAt = dontstarvemodDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dontstarvemodDescID is the schema descriptor for id field.
	dontstarvemodDescID := dontstarvemodFields[0].Descriptor()
	// dontstarvemod.DefaultID holds the default value on creation for the id field.
	dontstarvemod.DefaultID = dontstarvemodDescID.Default.(func() string)
}
