// Code generated by ent, DO NOT EDIT.

package dontstarvearchive

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dontstarvearchive type in the database.
	Label = "dont_starve_archive"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldClusterName holds the string denoting the cluster_name field in the database.
	FieldClusterName = "cluster_name"
	// FieldClusterPassword holds the string denoting the cluster_password field in the database.
	FieldClusterPassword = "cluster_password"
	// FieldClusterDescription holds the string denoting the cluster_description field in the database.
	FieldClusterDescription = "cluster_description"
	// FieldMaxPlayers holds the string denoting the max_players field in the database.
	FieldMaxPlayers = "max_players"
	// FieldPvp holds the string denoting the pvp field in the database.
	FieldPvp = "pvp"
	// FieldWorld holds the string denoting the world field in the database.
	FieldWorld = "world"
	// EdgeMods holds the string denoting the mods edge name in mutations.
	EdgeMods = "mods"
	// Table holds the table name of the dontstarvearchive in the database.
	Table = "dont_starve_archives"
	// ModsTable is the table that holds the mods relation/edge. The primary key declared below.
	ModsTable = "dont_starve_archive_mods"
	// ModsInverseTable is the table name for the DontStarveMod entity.
	// It exists in this package in order to avoid circular dependency with the "dontstarvemod" package.
	ModsInverseTable = "dont_starve_mods"
)

// Columns holds all SQL columns for dontstarvearchive fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRemark,
	FieldClusterName,
	FieldClusterPassword,
	FieldClusterDescription,
	FieldMaxPlayers,
	FieldPvp,
	FieldWorld,
}

var (
	// ModsPrimaryKey and ModsColumn2 are the table columns denoting the
	// primary key for the mods relation (M2M).
	ModsPrimaryKey = []string{"dont_starve_archive_id", "dont_starve_mod_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the DontStarveArchive queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByClusterName orders the results by the cluster_name field.
func ByClusterName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterName, opts...).ToFunc()
}

// ByClusterPassword orders the results by the cluster_password field.
func ByClusterPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterPassword, opts...).ToFunc()
}

// ByClusterDescription orders the results by the cluster_description field.
func ByClusterDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterDescription, opts...).ToFunc()
}

// ByMaxPlayers orders the results by the max_players field.
func ByMaxPlayers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPlayers, opts...).ToFunc()
}

// ByPvp orders the results by the pvp field.
func ByPvp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPvp, opts...).ToFunc()
}

// ByModsCount orders the results by mods count.
func ByModsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newModsStep(), opts...)
	}
}

// ByMods orders the results by mods terms.
func ByMods(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newModsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ModsTable, ModsPrimaryKey...),
	)
}
