// Code generated by ent, DO NOT EDIT.

package dontstarvearchive

import (
	"aurora-admin/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldUpdatedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldRemark, v))
}

// ClusterName applies equality check predicate on the "cluster_name" field. It's identical to ClusterNameEQ.
func ClusterName(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterName, v))
}

// ClusterPassword applies equality check predicate on the "cluster_password" field. It's identical to ClusterPasswordEQ.
func ClusterPassword(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterPassword, v))
}

// ClusterDescription applies equality check predicate on the "cluster_description" field. It's identical to ClusterDescriptionEQ.
func ClusterDescription(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterDescription, v))
}

// MaxPlayers applies equality check predicate on the "max_players" field. It's identical to MaxPlayersEQ.
func MaxPlayers(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldMaxPlayers, v))
}

// Pvp applies equality check predicate on the "pvp" field. It's identical to PvpEQ.
func Pvp(v bool) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldPvp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldUpdatedAt, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContainsFold(FieldRemark, v))
}

// ClusterNameEQ applies the EQ predicate on the "cluster_name" field.
func ClusterNameEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterName, v))
}

// ClusterNameNEQ applies the NEQ predicate on the "cluster_name" field.
func ClusterNameNEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldClusterName, v))
}

// ClusterNameIn applies the In predicate on the "cluster_name" field.
func ClusterNameIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldClusterName, vs...))
}

// ClusterNameNotIn applies the NotIn predicate on the "cluster_name" field.
func ClusterNameNotIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldClusterName, vs...))
}

// ClusterNameGT applies the GT predicate on the "cluster_name" field.
func ClusterNameGT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldClusterName, v))
}

// ClusterNameGTE applies the GTE predicate on the "cluster_name" field.
func ClusterNameGTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldClusterName, v))
}

// ClusterNameLT applies the LT predicate on the "cluster_name" field.
func ClusterNameLT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldClusterName, v))
}

// ClusterNameLTE applies the LTE predicate on the "cluster_name" field.
func ClusterNameLTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldClusterName, v))
}

// ClusterNameContains applies the Contains predicate on the "cluster_name" field.
func ClusterNameContains(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContains(FieldClusterName, v))
}

// ClusterNameHasPrefix applies the HasPrefix predicate on the "cluster_name" field.
func ClusterNameHasPrefix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasPrefix(FieldClusterName, v))
}

// ClusterNameHasSuffix applies the HasSuffix predicate on the "cluster_name" field.
func ClusterNameHasSuffix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasSuffix(FieldClusterName, v))
}

// ClusterNameIsNil applies the IsNil predicate on the "cluster_name" field.
func ClusterNameIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldClusterName))
}

// ClusterNameNotNil applies the NotNil predicate on the "cluster_name" field.
func ClusterNameNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldClusterName))
}

// ClusterNameEqualFold applies the EqualFold predicate on the "cluster_name" field.
func ClusterNameEqualFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEqualFold(FieldClusterName, v))
}

// ClusterNameContainsFold applies the ContainsFold predicate on the "cluster_name" field.
func ClusterNameContainsFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContainsFold(FieldClusterName, v))
}

// ClusterPasswordEQ applies the EQ predicate on the "cluster_password" field.
func ClusterPasswordEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterPassword, v))
}

// ClusterPasswordNEQ applies the NEQ predicate on the "cluster_password" field.
func ClusterPasswordNEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldClusterPassword, v))
}

// ClusterPasswordIn applies the In predicate on the "cluster_password" field.
func ClusterPasswordIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldClusterPassword, vs...))
}

// ClusterPasswordNotIn applies the NotIn predicate on the "cluster_password" field.
func ClusterPasswordNotIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldClusterPassword, vs...))
}

// ClusterPasswordGT applies the GT predicate on the "cluster_password" field.
func ClusterPasswordGT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldClusterPassword, v))
}

// ClusterPasswordGTE applies the GTE predicate on the "cluster_password" field.
func ClusterPasswordGTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldClusterPassword, v))
}

// ClusterPasswordLT applies the LT predicate on the "cluster_password" field.
func ClusterPasswordLT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldClusterPassword, v))
}

// ClusterPasswordLTE applies the LTE predicate on the "cluster_password" field.
func ClusterPasswordLTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldClusterPassword, v))
}

// ClusterPasswordContains applies the Contains predicate on the "cluster_password" field.
func ClusterPasswordContains(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContains(FieldClusterPassword, v))
}

// ClusterPasswordHasPrefix applies the HasPrefix predicate on the "cluster_password" field.
func ClusterPasswordHasPrefix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasPrefix(FieldClusterPassword, v))
}

// ClusterPasswordHasSuffix applies the HasSuffix predicate on the "cluster_password" field.
func ClusterPasswordHasSuffix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasSuffix(FieldClusterPassword, v))
}

// ClusterPasswordIsNil applies the IsNil predicate on the "cluster_password" field.
func ClusterPasswordIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldClusterPassword))
}

// ClusterPasswordNotNil applies the NotNil predicate on the "cluster_password" field.
func ClusterPasswordNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldClusterPassword))
}

// ClusterPasswordEqualFold applies the EqualFold predicate on the "cluster_password" field.
func ClusterPasswordEqualFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEqualFold(FieldClusterPassword, v))
}

// ClusterPasswordContainsFold applies the ContainsFold predicate on the "cluster_password" field.
func ClusterPasswordContainsFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContainsFold(FieldClusterPassword, v))
}

// ClusterDescriptionEQ applies the EQ predicate on the "cluster_description" field.
func ClusterDescriptionEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldClusterDescription, v))
}

// ClusterDescriptionNEQ applies the NEQ predicate on the "cluster_description" field.
func ClusterDescriptionNEQ(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldClusterDescription, v))
}

// ClusterDescriptionIn applies the In predicate on the "cluster_description" field.
func ClusterDescriptionIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldClusterDescription, vs...))
}

// ClusterDescriptionNotIn applies the NotIn predicate on the "cluster_description" field.
func ClusterDescriptionNotIn(vs ...string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldClusterDescription, vs...))
}

// ClusterDescriptionGT applies the GT predicate on the "cluster_description" field.
func ClusterDescriptionGT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldClusterDescription, v))
}

// ClusterDescriptionGTE applies the GTE predicate on the "cluster_description" field.
func ClusterDescriptionGTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldClusterDescription, v))
}

// ClusterDescriptionLT applies the LT predicate on the "cluster_description" field.
func ClusterDescriptionLT(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldClusterDescription, v))
}

// ClusterDescriptionLTE applies the LTE predicate on the "cluster_description" field.
func ClusterDescriptionLTE(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldClusterDescription, v))
}

// ClusterDescriptionContains applies the Contains predicate on the "cluster_description" field.
func ClusterDescriptionContains(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContains(FieldClusterDescription, v))
}

// ClusterDescriptionHasPrefix applies the HasPrefix predicate on the "cluster_description" field.
func ClusterDescriptionHasPrefix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasPrefix(FieldClusterDescription, v))
}

// ClusterDescriptionHasSuffix applies the HasSuffix predicate on the "cluster_description" field.
func ClusterDescriptionHasSuffix(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldHasSuffix(FieldClusterDescription, v))
}

// ClusterDescriptionIsNil applies the IsNil predicate on the "cluster_description" field.
func ClusterDescriptionIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldClusterDescription))
}

// ClusterDescriptionNotNil applies the NotNil predicate on the "cluster_description" field.
func ClusterDescriptionNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldClusterDescription))
}

// ClusterDescriptionEqualFold applies the EqualFold predicate on the "cluster_description" field.
func ClusterDescriptionEqualFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEqualFold(FieldClusterDescription, v))
}

// ClusterDescriptionContainsFold applies the ContainsFold predicate on the "cluster_description" field.
func ClusterDescriptionContainsFold(v string) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldContainsFold(FieldClusterDescription, v))
}

// MaxPlayersEQ applies the EQ predicate on the "max_players" field.
func MaxPlayersEQ(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldMaxPlayers, v))
}

// MaxPlayersNEQ applies the NEQ predicate on the "max_players" field.
func MaxPlayersNEQ(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldMaxPlayers, v))
}

// MaxPlayersIn applies the In predicate on the "max_players" field.
func MaxPlayersIn(vs ...int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIn(FieldMaxPlayers, vs...))
}

// MaxPlayersNotIn applies the NotIn predicate on the "max_players" field.
func MaxPlayersNotIn(vs ...int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotIn(FieldMaxPlayers, vs...))
}

// MaxPlayersGT applies the GT predicate on the "max_players" field.
func MaxPlayersGT(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGT(FieldMaxPlayers, v))
}

// MaxPlayersGTE applies the GTE predicate on the "max_players" field.
func MaxPlayersGTE(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldGTE(FieldMaxPlayers, v))
}

// MaxPlayersLT applies the LT predicate on the "max_players" field.
func MaxPlayersLT(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLT(FieldMaxPlayers, v))
}

// MaxPlayersLTE applies the LTE predicate on the "max_players" field.
func MaxPlayersLTE(v int) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldLTE(FieldMaxPlayers, v))
}

// MaxPlayersIsNil applies the IsNil predicate on the "max_players" field.
func MaxPlayersIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldMaxPlayers))
}

// MaxPlayersNotNil applies the NotNil predicate on the "max_players" field.
func MaxPlayersNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldMaxPlayers))
}

// PvpEQ applies the EQ predicate on the "pvp" field.
func PvpEQ(v bool) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldEQ(FieldPvp, v))
}

// PvpNEQ applies the NEQ predicate on the "pvp" field.
func PvpNEQ(v bool) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNEQ(FieldPvp, v))
}

// PvpIsNil applies the IsNil predicate on the "pvp" field.
func PvpIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldPvp))
}

// PvpNotNil applies the NotNil predicate on the "pvp" field.
func PvpNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldPvp))
}

// WorldIsNil applies the IsNil predicate on the "world" field.
func WorldIsNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldIsNull(FieldWorld))
}

// WorldNotNil applies the NotNil predicate on the "world" field.
func WorldNotNil() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.FieldNotNull(FieldWorld))
}

// HasMods applies the HasEdge predicate on the "mods" edge.
func HasMods() predicate.DontStarveArchive {
	return predicate.DontStarveArchive(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ModsTable, ModsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModsWith applies the HasEdge predicate on the "mods" edge with a given conditions (other predicates).
func HasModsWith(preds ...predicate.DontStarveMod) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(func(s *sql.Selector) {
		step := newModsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DontStarveArchive) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DontStarveArchive) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DontStarveArchive) predicate.DontStarveArchive {
	return predicate.DontStarveArchive(sql.NotPredicates(p))
}
