// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DontStarveAdmin is the predicate function for dontstarveadmin builders.
type DontStarveAdmin func(*sql.Selector)

// DontStarveArchive is the predicate function for dontstarvearchive builders.
type DontStarveArchive func(*sql.Selector)

// DontStarveMod is the predicate function for dontstarvemod builders.
type DontStarveMod func(*sql.Selector)
